### PR TITLE
ci: install `protoc` from repositories where possible

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

With the addition of more CI jobs, we are constantly running into API limits on setting up protoc. For all jobs that run on ubuntu, we can install it from `apt` instead.

On ubuntu 22.04, which is what `ubuntu-latest` points to, this installs `protoc v3.12.4`.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by MarcoPolo** [comment]
I’ve not looked closely, but let’s make sure this installs an up to date version. (Not something a year old)

**Comment by thomaseizinger** [comment]
> I’ve not looked closely, but let’s make sure this installs an up to date version. (Not something a year old)

It is only meant to be a temporary fix until we ship https://github.com/libp2p/rust-libp2p/pull/3066.

I just ran the command in a `ubuntu:jammy` (22.04) docker image and got protoc 3.12.4 which is about 2.5 years old. What are your concerns in installing an older version?

**Comment by MarcoPolo** [comment]
On my phone, but this has some context: https://github.com/libp2p/specs/issues/465#issuecomment-1272291524

**Comment by thomaseizinger** [comment]
> On my phone, but this has some context: [libp2p/specs#465 (comment)](https://github.com/libp2p/specs/issues/465#issuecomment-1272291524)

Thanks for linking this. At the moment, I'd just like to ease us from the burden of having constantly red CI jobs, PRs being dequeued from the merge queue and having to baby-sit and restart them constantly until we finally get a window where we don't hit the API limit upon installing protoc.

Long-term ,we are moving away from requiring protoc. I'd assume that by the time this decision is made and enforced across all libp2p implementations, we will have long merged #3066.

@libp2p/rust-libp2p-maintainers Do you agree with this?

**Comment by thomaseizinger** [comment]
Funnily enough, our interoperability tests install `protoc` through the exact same mechanism: https://github.com/libp2p/test-plans/blob/34b6eaeffd9f4a011e41ad8b2d8103229e750c12/ping/rust/Dockerfile#L4

I'd say that is an argument for doing it the same way here as well because it guarantees us that what we test interoperability on is actually the same thing as we write our unit tests etc for.

**Review by mxinden — APPROVED** [review]
I am fine moving forward here. Issues due to the protoc version should be detected at compile time, e.g. the proto3 optional issue would result in a compile time failure as our Rust code would expect an `Option`. https://github.com/libp2p/specs/issues/465#issuecomment-1272291524

**Comment by mxinden** [comment]
@Mergifyio refresh

**Comment by thomaseizinger** [comment]
I am backporting this to v0.49 because the actual backport is otherwise super painful.

**Comment by thomaseizinger** [comment]
@mergifyio backport rust-v0490-testplan

**Pull request merged**
