### PR TITLE
*: Prepare v0.49.0

### PR DESCRIPTION
**Pull request by mxinden**
# Description

In preparation for the `libp2p` `v0.49.0` release.

Waiting on:

- https://github.com/libp2p/rust-libp2p/pull/2928
- https://github.com/libp2p/test-plans/pull/41
- https://github.com/libp2p/rust-libp2p/pull/2932
- https://github.com/libp2p/rust-libp2p/pull/2934
- https://github.com/libp2p/rust-libp2p/pull/2974
- https://github.com/libp2p/rust-libp2p/pull/2960

## Open Questions

Anything else folks would like to block this release on?

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
We should definitely merge https://github.com/libp2p/rust-libp2p/pull/2960 before we release the next version.

**Comment by thomaseizinger** [comment]
Same with https://github.com/libp2p/rust-libp2p/pull/2974.

**Comment by mxinden** [comment]
If I am not mistaken, all blockers for this release have been resolved.

(In general, I don't think it makes sense to block a release on a feature. I much rather cut a new release for that feature once merged.)

@thomaseizinger @elenaf9 @jxs am I missing anything? Mind giving this a review?

**Review by melekes — APPROVED** [review]
👍

**Review by jxs — APPROVED** [review]
LGTM Max :)

**Review by thomaseizinger — APPROVED** [review]
LGTM!

I am gonna trigger another update so we can see the checks introduced with https://github.com/libp2p/rust-libp2p/pull/2647.

**Review by elenaf9 — APPROVED** [review]

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-autonat-v0.8.0
- libp2p-core-v0.37.0
- libp2p-dcutr-v0.7.0
- libp2p-deflate-v0.37.0
- libp2p-dns-v0.37.0
- libp2p-floodsub-v0.40.1
- libp2p-gossipsub-v0.42.1
- libp2p-identify-v0.40.0
- libp2p-kad-v0.41.0
- libp2p-mdns-v0.41.0
- libp2p-metrics-v0.10.0
- libp2p-mplex-v0.37.0
- libp2p-noise-v0.40.0
- libp2p-ping-v0.40.1
- libp2p-plaintext-v0.37.0
- libp2p-pnet-v0.22.1
- libp2p-relay-v0.13.0
- libp2p-rendezvous-v0.10.0
- libp2p-request-response-v0.22.1
- libp2p-swarm-derive-v0.30.1
- libp2p-swarm-v0.40.1
- libp2p-tcp-v0.37.0
- libp2p-uds-v0.36.0
- libp2p-wasm-ext-v0.37.0
- libp2p-websocket-v0.39.0
- libp2p-yamux-v0.41.0
- multistream-select-v0.12.0
- prost-codec-v0.2.0
- rw-stream-sink-v0.3.0
- v0.49.0

**Pull request merged**
