### PR TITLE
Support /dnsaddr in multiaddr

### PR DESCRIPTION
**Pull request by ackintosh**
closes https://github.com/libp2p/rust-libp2p/issues/967

📝 
- [multiaddr/DNSADDR.md at master · multiformats/multiaddr](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md)
- https://github.com/multiformats/go-multiaddr-dns/blob/0eb9e18d2fb65518efd1583d7bb91c6a12ffb1b4/resolve.go#L146

### CODE REVIEW

**Comment by ackintosh** [comment]
I am aware that a feature for dnsaddr should be added to [`transport`](https://github.com/libp2p/rust-libp2p/tree/master/transports) layer but I'm waiting and see the progress of https://github.com/libp2p/rust-libp2p/pull/1328 as the https://github.com/libp2p/rust-libp2p/pull/1328 has lots of changes. 🤔

**Comment by rklaehn** [comment]
Can this be warmed up? It is needed for reading the default ipfs bootstrap nodes...

I think it is fine to first allow multiaddrs like `/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN` to be parsed without having support for dnsaddr in the networking code. That could happen in a subsequent PR.

**Comment by ackintosh** [comment]
I'm working on this issue. (sorry for the delay...)

cc: @twittner @tomaka 
Please leave your comment if it's ok to merge this PR without the transport layer support. 🙏

**Comment by tomaka** [comment]
Yes, it's fine!

**Comment by ackintosh** [comment]
@tomaka Thanks for your comment! I've switched this PR to ready and have fixed conflicts between master.

**Pull request merged**
