### PR TITLE
chore: fix clippy

### PR DESCRIPTION
**Pull request by jxs**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Mind doing the dependency update in a separate PR? It would be great to have that one isolated :)

**Comment by jxs** [comment]
No worries Thomas, updated :). Though we will have to merge this one with the failing clippy because of the deprecated warning on `webpki-roots`

**Comment by thomaseizinger** [comment]
> No worries Thomas, updated :). Though we will have to merge this one with the failing clippy because of the deprecated warning on `webpki-roots` 

That is okay. I guess some dependency update introduced that and we didn't notice because clippy is not required to pass (we had that but it was a massive pain and it is only advisory ..)

**Comment by mxinden** [comment]
Upgrading https://github.com/libp2p/punchr/ I ran into the following issue:

```
error[E0599]: no method named `with_client_auth_cert` found for struct `ConfigBuilder` in the current scope
  --> /home/mxinden/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/d566f45/transports/tls/src/lib.rs:57:10
   |
49 |       let mut crypto = rustls::ClientConfig::builder()
   |  ______________________-
50 | |         .with_cipher_suites(verifier::CIPHERSUITES)
51 | |         .with_safe_default_kx_groups()
52 | |         .with_protocol_versions(verifier::PROTOCOL_VERSIONS)
...  |
56 | |         ))
57 | |         .with_client_auth_cert(vec![certificate], private_key)
   | |         -^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `with_no_client_auth`
   | |_________|
   | 
```

The following updates resolve the issue:

```
cargo update -p rustls@0.20.8
cargo update -p rustls@0.21.2
```

Maybe some others find this helpful.

**Comment by thomaseizinger** [comment]
That is surprising to me. Is this an error on our end? From a first look, this seems to be a semver violation by rustls?

**Comment by mxinden** [comment]
Not sure. Seems to be introduced through https://github.com/rustls/rustls/pull/1345.

**Comment by jxs** [comment]
> That is surprising to me. Is this an error on our end? From a first look, this seems to be a semver violation by rustls?

they deprecated `with_single_cert` and introduced `with_client_auth_cert` on a tiny (`0.21.1` to `0.21.2`) so it isn't a semver violation right? Could it have been @mxinden having a stale `Cargo.lock`, pulling the new changes and still using `0.21.1`?

**Comment by mxinden** [comment]
In case it is useful, another failure, this time on rust-libp2p-server. I don't think we need to act on this. I think requiring users to upgrade `rustls` is just fine.

https://github.com/mxinden/rust-libp2p-server/pull/255

**Pull request merged**
