### PR TITLE
*: Format with rustfmt

### PR DESCRIPTION
**Pull request by mxinden**
Using rustfmt across the rust-libp2p repository has been [a continuous ask from contributors and the community](https://github.com/libp2p/rust-libp2p/search?q=rustfmt&type=issues). While using rustfmt myself, I am mostly indifferent. That said, given that most of the Rust ecosystem uses rustfmt and given that using rustfmt lowers the barrier for newcomers, this pull request formats all of rust-libp2p and adds a CI step to enforce the formatting in the future (thanks to @thomaseizinger).

I went through most of the changes. As far as I can tell, none of the pointers as comments (e.g. `some code // [1]`) have been altered.

### CODE REVIEW

**Review by dvc94ch — APPROVED** [review]

**Review by wngr — APPROVED** [review]
Great quality-of-life improvement :-)

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
I will wait for https://github.com/libp2p/rust-libp2p/pull/2188 to merge first. Reviews on https://github.com/libp2p/rust-libp2p/pull/2188 would be very much appreciated.

**Comment by dvc94ch** [comment]
I'm afraid that if you wait for #2188 to be merged before merging #2188 this PR will never get merged ;)

**Comment by mxinden** [comment]
> I'm afraid that if you wait for #2188 to be merged before merging #2188 this PR will never get merged ;)

Haha, indeed. This is a tough one to solve :P 

I meant to reference https://github.com/libp2p/rust-libp2p/pull/2183 which should solve the puzzle.

**Pull request merged**
