### PR TITLE
Remove fqdn() function from libp2p-dns

### PR DESCRIPTION
**Pull request by tomaka**
Fix https://github.com/libp2p/rust-libp2p/issues/2022

See [this comment](https://github.com/libp2p/rust-libp2p/issues/2022#issuecomment-809733928)

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
Do I understand correctly that without `fqdn()`, i.e. without (falsely) making all domains fully-qualified domains, we do two queries for each domain, even though one might suffice for fully-qualified domains? Put differently, this change has a performance impact only, while restoring correctness across all cases?

**Comment by tomaka** [comment]
As far as I understand, yes

**Comment by mxinden** [comment]
@tomaka have you had the chance to test both the fully qualified and the not fully qualified case?

**Comment by tomaka** [comment]
I did not test this, as the fix seems obvious to me.
The `trust-dns` library expects a domain name. We do some pre-transformation on the domain name passed by the user. This PR removes this transformation so that `trust-dns` gets passed the exact value that the user requested.
If this introduces a bug, it can only either be in `trust-dns` or was already present before this PR.

**Review by mxinden — APPROVED** [review]
Just tested this with a non fully qualified domain locally with `DnsConfig::system()` which works as expected.

I can cut a new patch release of `libp2p-dns`. Is that good enough for you @montekki?

**Comment by montekki** [comment]
Yeah as soon as we can propagate it into the `polkadot` codebase

**Comment by mxinden** [comment]
`libp2p-dns` `v0.28.1` is [published](https://crates.io/crates/libp2p-dns/0.28.1) and [tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-dns-0.28.1). Thanks for the patch @tomaka.

**Pull request merged**
