### PR TITLE
ci(interop): Use run-interop-ping-test master latest hash

### PR DESCRIPTION
**Pull request by mxinden**
## Description

With https://github.com/libp2p/test-plans/pull/121 merged, we should be able to use master directly. This commit references the latest test-plans commit hash.

This includes
https://github.com/libp2p/test-plans/pull/121/commits/6d1aed2ed51b6376ffb4802bb29347d64f9c8694, thus allowing interop tests to run from fork pull requests.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] ~~A changelog entry has been made in the appropriate crates~~

### CODE REVIEW

**Comment by mxinden** [comment]
I am assuming that the specific git commit hash was meant to be temporary, thus changing to `master` here. @MarcoPolo and @thomaseizinger let me know if I understood this correctly.

**Review by thomaseizinger — DISMISSED** [review]
NACK

The specific commit was to make sure the repos don't break if test-plans changes. I'd like to keep it. Does dependabot not send update PRs for this?

**Comment by mxinden** [comment]
Dependabot has not send an update PR. I am assuming that this is due to the previous commit hash not being part of libp2p/test-plans `master` branch.

I will reference a git commit hash instead of `master` here instead.

**Comment by mxinden** [comment]
Retriggered `libp2p-swarm` test with flaky test (see https://github.com/libp2p/rust-libp2p/pull/3465).

@thomaseizinger pointing to a concrete git commit now, thus dismissing your review. Will merge to unblock other pull requests. Please still review when you have time.

**Review by thomaseizinger — APPROVED** [review]
Thanks Max!

**Pull request merged**
