### PR TITLE
chore: prepare v0.53.0

### LINKED ISSUE #4545: `v0.53` release
Tracking issue for the upcoming `v0.53` release to make sure we don't forget anything.

```[tasklist]
### PRs to include in final patch release
- [ ] https://github.com/libp2p/rust-libp2p/pull/4559
- [ ] https://github.com/libp2p/rust-libp2p/pull/4569
- [ ] https://github.com/libp2p/rust-libp2p/pull/4102
- [ ] https://github.com/libp2p/rust-libp2p/pull/4029
- [ ] https://github.com/libp2p/rust-libp2p/pull/4656
- [ ] https://github.com/libp2p/rust-libp2p/pull/4645
- [ ] https://github.com/libp2p/rust-libp2p/pull/4672
- [ ] https://github.com/libp2p/rust-libp2p/pull/4349
```

```[tasklist]
- [x] Mention transition to `tracing` in release notes on GitHub
- [x] Mention API improvements like `PollParameters` & `FromSwarm`
- [ ] https://github.com/libp2p/rust-libp2p/milestone/7
- [x] Remove all deprecated items
- [x] Mention more aggressive KeepAlive
- [ ] https://github.com/libp2p/rust-libp2p/pull/4581
```

### PR DESCRIPTION
**Pull request by mxinden**
## Notes & open questions

Closes https://github.com/libp2p/rust-libp2p/issues/4545

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
I published and tagged the following crates:

- futures-bounded-v0.2.1
- hole-punching-tests-v0.1.0
- libp2p-allow-block-list-v0.3.0
- libp2p-autonat-v0.12.0
- libp2p-connection-limits-v0.3.0
- libp2p-core-v0.41.0
- libp2p-dcutr-v0.11.0
- libp2p-dns-v0.41.0
- libp2p-floodsub-v0.44.0
- libp2p-gossipsub-v0.46.0
- libp2p-identify-v0.44.0
- libp2p-kad-v0.45.0
- libp2p-mdns-v0.45.0
- libp2p-memory-connection-limits-v0.2.0
- libp2p-metrics-v0.14.0
- libp2p-mplex-v0.41.0
- libp2p-noise-v0.44.0
- libp2p-perf-v0.3.0
- libp2p-ping-v0.44.0
- libp2p-plaintext-v0.41.0
- libp2p-pnet-v0.24.0
- libp2p-quic-v0.10.0
- libp2p-relay-v0.17.0
- libp2p-rendezvous-v0.14.0
- libp2p-request-response-v0.26.0
- libp2p-swarm-derive-v0.34.0
- libp2p-swarm-test-v0.3.0
- libp2p-swarm-v0.44.0
- libp2p-tcp-v0.41.0
- libp2p-tls-v0.3.0
- libp2p-uds-v0.40.0
- libp2p-upnp-v0.2.0
- libp2p-v0.53.0
- libp2p-websocket-v0.43.0
- libp2p-websocket-websys-v0.3.0
- libp2p-webtransport-websys-v0.2.0
- libp2p-yamux-v0.45.0

I was not able to publish `libp2p-webrtc-websys`:

```
error[E0277]: `?` couldn't convert the error to `error::Error`
  --> src/upgrade.rs:51:97
   |
51 |     let peer_id = noise::outbound(id_keys, channel, remote_fingerprint, local_fingerprint).await?;
   |                                                                                                 ^ the trait `From<libp2p_noise::Error>` is not implemented for `error::Error`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following other types implement trait `From<T>`:
             <error::Error as From<wasm_bindgen::JsValue>>
             <error::Error as From<libp2p_noise::Error>>
             <error::Error as From<std::io::Error>>
             <error::Error as From<String>>
   = note: required for `Result<(PeerId, Connection), error::Error>` to implement `FromResidual<Result<Infallible, libp2p_noise::Error>>`

For more information about this error, try `rustc --explain E0277`.
```

I will debug this further tomorrow. //CC @thomaseizinger  in case you have an idea.

**Comment by thomaseizinger** [comment]
> I will debug this further tomorrow. //CC @thomaseizinger in case you have an idea.

Might perhaps be a missing `std` feature flag somewhere so it doesn't implement `std::error::Error`?

**Comment by mxinden** [comment]
> > I will debug this further tomorrow. //CC @thomaseizinger in case you have an idea.
> 
> Might perhaps be a missing `std` feature flag somewhere so it doesn't implement `std::error::Error`?

Turns out, we never actually bumped the `libp2p-webrtc-websys` version:

https://github.com/libp2p/rust-libp2p/blob/dbfda10e3f0f649c6f8556d0afc71bf525968104/transports/webrtc-websys/Cargo.toml#L11

`v0.2.0-alpha` is already on crates.io.

**Comment by thomaseizinger** [comment]
I think that is because we exclude alphas anyway and can release them at any time, yeah?

**Pull request merged**
