### PR TITLE
README.md: Add elenaf9 to Maintainers

### PR DESCRIPTION
**Pull request by mxinden**
Would need your approval @elenaf9  :slightly_smiling_face:

### CODE REVIEW

**Review by elenaf9 — APPROVED** [review]
Thanks!

**Review by thomaseizinger — APPROVED** [review]
Welcome! :)

**Comment by dignifiedquire** [comment]
🎉

**Comment by mxinden** [comment]
> Would need your approval @elenaf9 slightly_smiling_face

And hit the merge button :)

**Pull request merged**
