### PR TITLE
chore: prepare libp2p v0.52.0 release

### PR DESCRIPTION
**Pull request by mxinden**
## Notes & open questions

Release milestone https://github.com/libp2p/rust-libp2p/milestone/6.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Missing removal of all `- unreleased` postfixes.

**Comment by mxinden** [comment]
How about introducing two sections. A _TL;DR_ section documenting the gotchas, i.e. the things you need to know before upgrading and a longer section advertising the cool new features that this release brings with it? I feel like while our current changelogs show what changed, they don't tell the story of why someone should upgrade.

**Comment by thomaseizinger** [comment]
> How about introducing two sections. A _TL;DR_ section documenting the gotchas, i.e. the things you need to know before upgrading and a longer section advertising the cool new features that this release brings with it? I feel like while our current changelogs show what changed, they don't tell the story of why someone should upgrade.

I think changelogs should be just that, a log of changes. I see them as a point of reference.

Advertising new features and releases should be done in blogposts or other marketing material.

I do think that we should sort the changelogs by priority. Ideally, we'd also adopt the keep-a-changelog format.

**Comment by thomaseizinger** [comment]
> Missing removal of all `- unreleased` postfixes.

I did that for all crates **that are included in the `0.52`** release, i.e. I did not remove it for `libp2p-quic` and `libp2p-webrtc`.

**Comment by mxinden** [comment]
Removed the call-outs section. I would still like to highlight some subtle changes in the GitHub release page.

@thomaseizinger anything missing here? If not, mind approving?

**Comment by thomaseizinger** [comment]
> Removed the call-outs section. I would still like to highlight some subtle changes in the GitHub release page.

Sure thing! I am still in favor of writing a blog post as well. I should be able to spend some cycles on that later today.

> @thomaseizinger anything missing here?

Don't think so.

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
Our move to _workspace dependencies_ seems to be problematic when releasing.

Releasing `libp2p-core` fails as it depends on `multistream-select`:

```
➜  core git:(master) cargo release publish --execute          
warning: push target `origin/master` doesn't exist
Publish libp2p-core 0.40.0? [y/N] 
y
  Publishing libp2p-core
    Updating crates.io index
   Packaging libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/core)
   Verifying libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/core)
    Updating crates.io index
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `multistream-select = "^0.13.0"`
  candidate versions found which didn't match: 0.12.1, 0.12.0, 0.11.0, ...
  location searched: crates.io index
  required by package `libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/target/package/libp2p-core-0.40.0)`
  perhaps a crate was updated and forgotten to be re-vendored?
```

Releasing `multistream-select` fails as it depends, as a dev-dependency, on `libp2p-core`:

```
➜  multistream-select git:(master) cargo release publish  --execute        
warning: push target `origin/master` doesn't exist
Publish multistream-select 0.13.0? [y/N] 
y
  Publishing multistream-select
    Updating crates.io index
   Packaging multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/misc/multistream-select)
   Verifying multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/misc/multistream-select)
    Updating crates.io index
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `libp2p-core = "^0.40.0"`
  candidate versions found which didn't match: 0.39.2, 0.39.1, 0.39.0, ...
  location searched: crates.io index
  required by package `multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/target/package/multistream-select-0.13.0)`
  perhaps a crate was updated and forgotten to be re-vendored?
```

Off the top of my head this is due to `multistream-select` specifying `libp2p-core` as a _workspace dependency_ in its dev dependencies. The workspace dependency `libp2p-core` is defined with a version in the root `Cargo.toml`.

**Comment by mxinden** [comment]
@thomaseizinger I am logging off soon. Will debug this more tomorrow. Let me know in case you have any ideas in the meantime.

**Comment by thomaseizinger** [comment]
> Our move to _workspace dependencies_ seems to be problematic when releasing.
> 
> Releasing `libp2p-core` fails as it depends on `multistream-select`:
> 
> ```
> ➜  core git:(master) cargo release publish --execute          
> warning: push target `origin/master` doesn't exist
> Publish libp2p-core 0.40.0? [y/N] 
> y
>   Publishing libp2p-core
>     Updating crates.io index
>    Packaging libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/core)
>    Verifying libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/core)
>     Updating crates.io index
> error: failed to verify package tarball
> 
> Caused by:
>   failed to select a version for the requirement `multistream-select = "^0.13.0"`
>   candidate versions found which didn't match: 0.12.1, 0.12.0, 0.11.0, ...
>   location searched: crates.io index
>   required by package `libp2p-core v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/target/package/libp2p-core-0.40.0)`
>   perhaps a crate was updated and forgotten to be re-vendored?
> ```
> 
> Releasing `multistream-select` fails as it depends, as a dev-dependency, on `libp2p-core`:
> 
> ```
> ➜  multistream-select git:(master) cargo release publish  --execute        
> warning: push target `origin/master` doesn't exist
> Publish multistream-select 0.13.0? [y/N] 
> y
>   Publishing multistream-select
>     Updating crates.io index
>    Packaging multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/misc/multistream-select)
>    Verifying multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/misc/multistream-select)
>     Updating crates.io index
> error: failed to verify package tarball
> 
> Caused by:
>   failed to select a version for the requirement `libp2p-core = "^0.40.0"`
>   candidate versions found which didn't match: 0.39.2, 0.39.1, 0.39.0, ...
>   location searched: crates.io index
>   required by package `multistream-select v0.13.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/target/package/multistream-select-0.13.0)`
>   perhaps a crate was updated and forgotten to be re-vendored?
> ```
> 
> Off the top of my head this is due to `multistream-select` specifying `libp2p-core` as a _workspace dependency_ in its dev dependencies. The workspace dependency `libp2p-core` is defined with a version in the root `Cargo.toml`. 

Yeah, cyclic dependencies are not good, even if dev-dependencies technically allow them. We should test `multistream-select` without depending on `libp2p-core`. Off the top of my head, we only have this dependency because we test the compatibility with the "upgrade" mechanics in `libp2p-core`. IMO this is ensured anyway by us having it in our workspace in a mono-repo.

**Comment by thomaseizinger** [comment]
I think an alternative fix to https://github.com/libp2p/rust-libp2p/pull/4090 could be use path dependencies for all workspace dependencies _for `dev-dependencies` only_.

**Comment by thomaseizinger** [comment]
> I think an alternative fix to #4090 could be use path dependencies for all workspace dependencies _for `dev-dependencies` only_.

This seems to be the recommended way of dealing with this: https://github.com/rust-lang/futures-rs/pull/2305. The original issue is here: https://github.com/rust-lang/cargo/issues/4242

Reading that thread, it appeared to me that this means that our crate's test won't run in a crater run then because it is missing important dependencies.

I think it would be good to only use `path` dependencies for `dev-dependencies` where absolutely necessary. We should strive for our crates to be useful in crater runs.

**Comment by thomaseizinger** [comment]
> I think an alternative fix to #4090 could be use path dependencies for all workspace dependencies _for `dev-dependencies` only_.

I coded that up here: https://github.com/libp2p/rust-libp2p/pull/4091

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-allow-block-list-v0.2.0
- libp2p-autonat-v0.11.0
- libp2p-connection-limits-v0.2.0
- libp2p-core-v0.40.0
- libp2p-dcutr-v0.10.0
- libp2p-deflate-v0.40.0
- libp2p-dns-v0.40.0
- libp2p-floodsub-v0.43.0
- libp2p-gossipsub-v0.45.0
- libp2p-identify-v0.43.0
- libp2p-kad-v0.44.0
- libp2p-mdns-v0.44.0
- libp2p-metrics-v0.13.0
- libp2p-mplex-v0.40.0
- libp2p-noise-v0.43.0
- libp2p-perf-v0.2.0
- libp2p-ping-v0.43.0
- libp2p-plaintext-v0.40.0
- libp2p-pnet-v0.23.0
- libp2p-quic-v0.8.0-alpha
- libp2p-relay-v0.16.0
- libp2p-rendezvous-v0.13.0
- libp2p-request-response-v0.25.0
- libp2p-swarm-derive-v0.33.0
- libp2p-swarm-test-v0.2.0
- libp2p-swarm-v0.43.0
- libp2p-tcp-v0.40.0
- libp2p-tls-v0.2.0
- libp2p-uds-v0.39.0
- libp2p-v0.52.0
- libp2p-wasm-ext-v0.40.0
- libp2p-webrtc-v0.5.0-alpha
- libp2p-websocket-v0.42.0
- libp2p-yamux-v0.44.0
- multistream-select-v0.13.0
- quick-protobuf-codec-v0.2.0
- rw-stream-sink-v0.4.0

**Comment by thomaseizinger** [comment]
Submitted to TWIR: https://github.com/rust-lang/this-week-in-rust/pull/4446

**Pull request merged**
