### PR TITLE
Kademlia Client mode

### LINKED ISSUE #2032: Support client mode for Kademlia implementation
From what I understand from https://github.com/libp2p/rust-libp2p/discussions/2025#discussioncomment-570443 the Kademlia implementation does not support client mode. Client mode is quite useful as it allows lower quality (e.g. intermittent availability, high latency, low bandwidth, low CPU/RAM/Storage, etc.) nodes to utilize the DHT for discovery without decreasing the quality of the network.

This feature has been very helpful in go-libp2p and in the various consumers of it such as go-ipfs.

---

To implement client mode all that is really required is that the node does not advertise the DHT protocol (e.g. `/ipfs/kad/1.0.0`). Additionally, if the node is able to switch between client and server mode at runtime then updates to the supported protocols should be communicated via `identify-push`/`identify-delta`.

Once we have the basic client-server mode switching then as a follow up it might be a good idea to, as go-libp2p does, have an "automatic" mode that switches between client and server mode based on educated guessing about what is appropriate for the user (e.g. peers behind relays probably shouldn't be servers, and peers who haven't been online for a while and are stable probably shouldn't either).

### PR DESCRIPTION
**Pull request by MarcoPolo**
## Context

Continuation of https://github.com/libp2p/rust-libp2p/pull/2184 and fixes https://github.com/libp2p/rust-libp2p/issues/2032.

See https://github.com/libp2p/specs/blob/master/kad-dht/README.md#client-and-server-mode for the specs on client mode.

Most of this diff is tests :)

## Warning

This changes the behavior of Kademlia's handler's `inject_fully_negotiated_inbound`. Namely before this change we assumed the dialer spoke the Kademlia protocol, but now we don't. This is because we don't know if the dialer is a client and therefore would not respond to our request or a server and would.

Before we merge this change I think we should make some other change that would let a node know if another node supports kademlia. Currently you'd have to wire up the identify behavior and manually call `add_address`.

### CODE REVIEW

**Comment by mxinden** [comment]
For those interested, this is now deployed on kademlia-exporter.max-inden.de/. See dashboard below to compare with vanilla `libp2p` `v0.44.0`.

https://kademlia-exporter.max-inden.de/d/Pfr0Fj6Mk/rust-libp2p?orgId=1&var-data_source=Prometheus&var-instance=kademlia-exporter-ipfs-client-mode:8080&var-instance=kademlia-exporter-ipfs:8080

**Comment by Fomalhauthmj** [comment]
What else shall we do for this pr merged into master?

**Comment by MarcoPolo** [comment]
I wrote in the PR description:
> Before we merge this change I think we should make some other change that would let a node know if another node supports kademlia. Currently you'd have to wire up the identify behavior and manually call add_address.

I think this is still true. Right now if we merge this change we could negatively impact the routing table of servers. Since before they would add a peer when the peer reached out, now they would only do that on dial out or if the peer was manually added. Of course the peer could have been unreachable anyways (say behind a nat) so maybe it's a wash. Still it would be good to have a mechanism that lets the old behavior keep working, instead of changing it completely.

I have some ideas on the change that would be required to get this working. And I'll make an issue that outlines it so we can track the blocker properly.

**Comment by mxinden** [comment]
> I have some ideas on the change that would be required to get this working. And I'll make an issue that outlines it so we can track the blocker properly.

Corresponding issue based on a past meeting with @MarcoPolo: https://github.com/libp2p/rust-libp2p/issues/2680

@MarcoPolo and @ all additional input is welcome.

**Comment by MarcoPolo** [comment]
Thanks Max, that's exactly what I had in mind :)

**Comment by dariusc93** [comment]
Any updates on this or what would need need to be done?

**Comment by mxinden** [comment]
We would want to do https://github.com/libp2p/rust-libp2p/issues/2680 first in order to address the "warning" section in the initial pull request description. @dariusc93 let me know if that (a) makes sense and (b) whether you would be interested working on any of it.

**Comment by thomaseizinger** [comment]
Setting this to draft until we can proceed.

**Comment by thomaseizinger** [comment]
Closing this as we will likely ship this in a different PR, thanks kicking it off @MarcoPolo !

See https://github.com/libp2p/rust-libp2p/pull/3651 and related PRs for further progress!

**Pull request closed without merging**
