### PR TITLE
chore: prepare libp2p-swarm v0.43.1 and libp2p-kad v0.44.2

### PR DESCRIPTION
**Pull request by mxinden**
## Notes & open questions

//CC @joshuef 

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by joshuef** [comment]
I was looking here to see if I could be of use in w/ any bugs found in CI, but it looks like it's just an intermittent networking issue: https://github.com/libp2p/rust-libp2p/actions/runs/5505954842/jobs/10034001289?pr=4166

So i think restarting that and we'd be all ✅ here.

**Review by thomaseizinger — APPROVED** [review]
LGTM

Perhaps we should add some automation that we can trigger with a naming convention or something that automatically invokes `cargo release` after such a release PR?

**Comment by gurinderu** [comment]
When are you going to release it?

**Comment by mxinden** [comment]
Tagged and published.

//CC @dariusc93 @joshuef @gurinderu

**Pull request merged**
