### PR TITLE
chore: prepare libp2p v0.52.3

### PR DESCRIPTION
**Pull request by mxinden**
## Description

- Addresses TLS CVE:
  - https://github.com/libp2p/rust-libp2p/pull/4381
  - https://github.com/libp2p/rust-libp2p/pull/4378
- Stable QUIC https://github.com/libp2p/rust-libp2p/pull/4325
- New rust-libp2p-server release https://github.com/libp2p/rust-libp2p/pull/4311

## Notes & open questions

@thomaseizinger @jxs any objections?

//CC @MOZGIII

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by jxs** [comment]
No no Max, thanks for the fast diligence! :rocket:

**Review by jxs — APPROVED** [review]

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
> Mergify doesn't have permission to update
> For security reasons, Mergify can't update this pull request. Try updating locally.
> GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/cache-factory.yml without workflows permission
>     err-code: 965D3

Surprising. Did we change mergify's permissions in https://github.com/libp2p/github-mgmt? @thomaseizinger this would explain the failures we have seen with pull requests from external contributors.

**Comment by thomaseizinger** [comment]
> > Mergify doesn't have permission to update
> > For security reasons, Mergify can't update this pull request. Try updating locally.
> > GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/cache-factory.yml without workflows permission
> > err-code: 965D3
> 
> Surprising. Did we change mergify's permissions in [libp2p/github-mgmt](https://github.com/libp2p/github-mgmt)? @thomaseizinger this would explain the failures we have seen with pull requests from external contributors.

I am not aware of any changes. I think what is happening here is that the required update of the branch will pull in the latest commit on master: https://github.com/libp2p/rust-libp2p/commit/4284caeef0f56495d2b53cfa27c193aba3fa1593

That one changes a workflow file which might cause this problem?

**Review by MOZGIII — APPROVED** [review]

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-noise-v0.43.1
- libp2p-quic-v0.9.2
- libp2p-tls-v0.2.1
- libp2p-v0.52.3
- libp2p-websocket-v0.42.1


Note that libp2p-server is missing. I will follow-up with a pull request.

**Pull request merged**
