### PR TITLE
[multistream-select] Fix `ls` response encoding/decoding (spec-compliance).

### PR DESCRIPTION
**Pull request by romanb**
This is step 2 of addressing https://github.com/libp2p/rust-libp2p/issues/1795. It changes the `ls` response encoding/decoding according to the spec, that is (line breaks only for ease of reading):

```
<varint-ls-response-length>
<varint-protocol-length><protocol>\n
<varint-protocol-length><protocol>\n
# ...more protocols
\n
```

Incidentally, since `ls` responses are always terminated with a line feed and thus end with two line feeds (one for the last protocol and one for the entire message), we no longer need the artificial protocol length limit that was introduced earlier in order to ensure disambiguation of `ls` responses that contain a single protocol and singular protocol responses / confirmations as the latter can never end with a double line feed.

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
This looks good to me.

Instead of merging already, I would delay the merge. In case we have an urgent feature but `rust-libp2p` `0.29` is not yet widely deployed, we can release right off of master. What do you think?

**Comment by romanb** [comment]
Sounds ok to me.

**Comment by romanb** [comment]
I would like to include this in the next release, if there are no objections.

**Comment by mxinden** [comment]
> I would like to include this in the next release, if there are no objections.

No objections from my side.

**Pull request merged**
