### PR TITLE
[WIP] Check OS and install for Ubuntu and Manjaro, fix warnings

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks for the PR, but I'm not sure we want to complexify the scripts, as these scripts are not meant to be run as long as you don't modify the `.proto` files.

**Comment by tomaka** [comment]
Ultimately, the correct way to do this is to generate this as part of the compilation thanks to a Rust crate.
In practice this isn't possible (we tried and reverted) because of https://github.com/rust-lang/rfcs/issues/752

**Comment by Vurich** [comment]
You can still run these scripts on other distributions by installing docker before running them. As @tomaka says, although that's not ideal it's better than adding complexity to (notoriously error-prone) shell scripts.

**Comment by tomaka** [comment]
I'm going to close this as both stable and not-the-right-solution.

**Pull request closed without merging**
