### PR TITLE
chore(ci): check rustfmt with nightly toolchain

### PR DESCRIPTION
**Pull request by elenaf9**
## Description

Some of our rustfmt rules aren't stable yet. Thus our rustfmt CI check should run on nightly.  

## Notes & open questions

Depends on #5742.

I am not super familiar with CI workflows. Can/ should this be solved differently?

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~A changelog entry has been made in the appropriate crates~~

### CODE REVIEW

**Comment by kamuik16** [comment]
run: `cargo fmt -- --check` -> run: `cargo +nightly fmt -- --check` I think.

**Comment by elenaf9** [comment]
> run: `cargo fmt -- --check` -> run: `cargo +nightly fmt -- --check` I think.

Isn't this implicitly done because we directly install the `nightly` toolchain? The rustfmt job on this PR fails as expected on master with the current change: https://github.com/libp2p/rust-libp2p/actions/runs/12329671999/job/34414253861?pr=5743.

**Comment by kamuik16** [comment]
> > run: `cargo fmt -- --check` -> run: `cargo +nightly fmt -- --check` I think.
> 
> Isn't this implicitly done because we directly install the `nightly` toolchain? The rustfmt job on this PR fails as expected on master with the current change: https://github.com/libp2p/rust-libp2p/actions/runs/12329671999/job/34414253861?pr=5743.

not that I know of, but I could be wrong.

**Review by jxs — COMMENTED** [review]
Thanks for going ahead with this Elena, I noticed when I ran locally tat there were files needing `fmt`. 
We just need to run `cargo fmt` now so for the CI to pass

**Comment by elenaf9** [comment]
> Thanks for going ahead with this Elena, I noticed when I ran locally tat there were files needing `fmt`.
> We just need to run `cargo fmt` now so for the CI to pass

Should be fixed now with #5742 merged?

**Review by jxs — APPROVED** [review]

**Pull request merged**
