### PR TITLE
chore(kad): remove deprecated module `record`

### PR DESCRIPTION
**Pull request by mxinden**
## Description

Deprecated in #3738.
Follow up to #3896.
Part of #3647.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
@tcoratger an @thomaseizinger can you take a look here?

**Comment by thomaseizinger** [comment]
> @tcoratger an @thomaseizinger can you take a look here?

Yeah, at the time we left this one because it is not obvious how to expose the record store etc so everything has nice names.

I'd be okay to leave this one for later, perhaps open a dedicated issue about it.

**Review by thomaseizinger — APPROVED** [review]
I think the interface is good enough.

**Comment by thomaseizinger** [comment]
@mxinden Still some Ci failures.

**Comment by mxinden** [comment]
Thanks!

**Pull request merged**
