### PR TITLE
chore: enforce `unreachable_pub` lint

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

The `unreachable_pub` lint makes us aware of uses of `pub` that are not actually reachable from the crate root. This is considered good because it means reading a `pub` somewhere means it is actually public API. Some of our crates are quite large and keeping their entire API surface in your head is difficult.

We should strive for most items being `pub(crate)`. This lint helps us enforce that.

## Notes & open questions

~Draft because not yet complete. There is a lot of code to go through so I think we want some kind of automation to do this for us.~

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
I am in favor of this.

**Comment by thomaseizinger** [comment]
Another data point for this: https://github.com/libp2p/rust-libp2p/issues/3741

**Comment by thomaseizinger** [comment]
@mxinden: Here is the initial version of enforcing this lint. I've applied most of the fixes with a script. Some of the `pub(crate)` could potentially also be just private. I didn't bother going through it all because I am not convinced that it matters other than for aesthetic reasons.

What is a bit surprising but also great is that fact that we seemed to correctly export all structs and not miss anything that is actually unreachable.

**Comment by thomaseizinger** [comment]
I am also adding the script I used to fix the warnings. I imagine once we remove some deprecations and / or add new modules, it might come in handy again.

Please don't judge me for my poor Python skills :see_no_evil:

**Review by mxinden — APPROVED** [review]
Thank you!

**Pull request merged**
