### PR TITLE
feat(kad): only dial if not connected AND not dialing

### PR DESCRIPTION
**Pull request by joshuef**
I was looking about our code and noticed we still used the old DialCondition (before the change to not dialling NOR connected as default) and thought I'd double check in libp2p. 

These places looked a bit suss and we can perhaps rely on the defaults here?

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
I believe this is fine. Will let @thomaseizinger take a final look.

**Review by thomaseizinger — APPROVED** [review]
LGTM but needs changelog entry and version bump!

**Comment by jxs** [comment]
friendly ping @joshuef

**Comment by joshuef** [comment]
Ah! forgot all about this. That's updated with master and a changelog entry added now 🙇

**Comment by jxs** [comment]
cargo deny is unrelated, submitted https://github.com/libp2p/rust-libp2p/pull/5293 to address it

**Review by jxs — APPROVED** [review]

**Pull request merged**
