### PR TITLE
docs: prepare v0.51.0

### PR DESCRIPTION
**Pull request by mxinden**
## Description

A large release with lots of changes I am looking forward to. Sorry for the long release cadence.

Anything folks would like to see included that is not yet in `master`? As usual I would like to only block on bug fixes.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
We said https://github.com/libp2p/rust-libp2p/pull/3254 should make it in otherwise we've landed only all the preparation work and not the actual feature :)

**Comment by mxinden** [comment]
@thomaseizinger with #3254 merged, anything else you would like to see included?

**Comment by thomaseizinger** [comment]
> @thomaseizinger with #3254 merged, anything else you would like to see included?

Nope, all good from my end!

**Comment by mxinden** [comment]
Published and tagged the following crates with @galargh and @laurentsenta:

- libp2p-autonat-v0.10.0
- libp2p-core-v0.39.0
- libp2p-dcutr-v0.9.0
- libp2p-deflate-v0.39.0
- libp2p-dns-v0.39.0
- libp2p-floodsub-v0.42.0
- libp2p-gossipsub-v0.44.0
- libp2p-identify-v0.42.0
- libp2p-kad-v0.43.0
- libp2p-mdns-v0.43.0
- libp2p-metrics-v0.12.0
- libp2p-mplex-v0.39.0
- libp2p-noise-v0.42.0
- libp2p-ping-v0.42.0
- libp2p-plaintext-v0.39.0
- libp2p-quic-v0.7.0-alpha.2
- libp2p-relay-v0.15.0
- libp2p-rendezvous-v0.12.0
- libp2p-request-response-v0.24.0
- libp2p-swarm-derive-v0.32.0
- libp2p-swarm-v0.42.0
- libp2p-tcp-v0.39.0
- libp2p-tls-v0.1.0-alpha.2
- libp2p-uds-v0.38.0
- libp2p-wasm-ext-v0.39.0
- libp2p-webrtc-v0.4.0-alpha.2
- libp2p-websocket-v0.41.0
- libp2p-yamux-v0.43.0
- v0.51.0

**Comment by mxinden** [comment]
//CC @jsantell and @cdata (sorry for the delay)

**Pull request merged**
