### PR TITLE
Update changelogs for prost dep update

### PR DESCRIPTION
**Pull request by divagant-martian**
# Description
Patch changelogs for #2788

## Links to any relevant issues
#2848 

## Open Questions
na

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation **does not apply**
- [ ] I have added tests that prove my fix is effective or that my feature works **does not apply**
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Thank you @divagant-martian!

**Comment by dignifiedquire** [comment]
thanks for the update. just a general note this is really painful when using libp2p now, as all ci flows have to be updated to manually install protoc, really unfortunate for downstream users

**Comment by mxinden** [comment]
Agreed @dignifiedquire, though I don't see a solution. Do you? 

I don't think this is libp2p specific, but applies to any application using `prost`.

**Comment by dignifiedquire** [comment]
agree it is a general prost problem, one idea I had is to make a rust crate that brings protoc with it, so one could include in its build deps

**Comment by jxs** [comment]
It seems https://github.com/tokio-rs/prost/pull/620 addresses that, but has been stagnant since https://github.com/tokio-rs/prost/pull/657

**Pull request merged**
