### PR TITLE
feat(.editorconfig): set `insert_final_newline` to true

### PR DESCRIPTION
**Pull request by mxinden**
## Description

Instructs editors to insert a newline at the end of a file and thus prevents GitHub flagging the missing newline.

## Notes

Follow up to https://github.com/libp2p/rust-libp2p/pull/3508/files#r1129123820.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@obi1kenobi Seems like the caching I implemented needs some invalidation rules around the rustdoc version!

Happy to send a fix with some guidance.

**Comment by obi1kenobi** [comment]
Whoops! Would love a fix if you have the time. I'm currently traveling so
I'm not sure when I'll be able to dig into it myself.

Do you think overwriting older rustdoc is better, or keeping multiple
rustdoc version copies is better? I can see pros and cons both ways.

**Comment by thomaseizinger** [comment]
> Whoops! Would love a fix if you have the time. I'm currently traveling so I'm not sure when I'll be able to dig into it myself. Do you think overwriting older rustdoc is better, or keeping multiple rustdoc version copies is better? I can see pros and cons both ways.

I think keeping multiple copies is better. We also need to figure out how to properly invalidate the cache. At the moment, I have a cache key is only based on the crate version but we'd need to incorporate the rustdoc version too now.

**Comment by thomaseizinger** [comment]
> Whoops! Would love a fix if you have the time. I'm currently traveling so I'm not sure when I'll be able to dig into it myself. Do you think overwriting older rustdoc is better, or keeping multiple rustdoc version copies is better? I can see pros and cons both ways.

I started by opening an issue: https://github.com/obi1kenobi/cargo-semver-checks/issues/415

**Pull request merged**
