### PR TITLE
Update libp2p-rendezvous to fix build on nightly

### PR DESCRIPTION
**Pull request by kpp**
Fix https://github.com/libp2p/rust-libp2p/issues/2225

### CODE REVIEW

**Comment by whereistejas** [comment]
haha, I was about to submit the same PR, myself.

**Comment by thomaseizinger** [comment]
`libp2p-rendezvous` is not released yet so the version doesn't need to be bumped!

Otherwise LGTM.

We need a CI to check against failure on nightly.

**Review by mxinden — APPROVED** [review]
Thanks @kpp!

**Comment by dvc94ch** [comment]
do we need three different PR's to fix the build on master? I'd suggest adding the clippy commit and updating clang to v11 in this PR. if it takes a week to review a PR it'll take three weeks to review three PR's.

**Pull request merged**
