### PR TITLE
chore(README): update maintainer list

### PR DESCRIPTION
**Pull request by elenaf9**
I am not an active maintainer anymore. 
To avoid confusion, I am removing myself from the maintainer list in the README.

### CODE REVIEW

**Review by thomaseizinger — DISMISSED** [review]
Very sad but better to reflect the current state.

**Review by mxinden — DISMISSED** [review]
Crossposting here:

> Sad to see this pull request.
>
> I think I am speaking for all libp2p folks when I say that you are welcome back on the rust-libp2p Maintainers group anytime.
>
> Danke fuer die tolle Arbeit!

https://github.com/libp2p/github-mgmt/pull/143

**Comment by mxinden** [comment]
Also CI doesn't seem to approve :stuck_out_tongue:

**Comment by elenaf9** [comment]
> Crossposting here:
> 
> > Sad to see this pull request.
> > I think I am speaking for all libp2p folks when I say that you are welcome back on the rust-libp2p Maintainers group anytime.
> > Danke fuer die tolle Arbeit!
> 
> [libp2p/github-mgmt#143](https://github.com/libp2p/github-mgmt/pull/143)

Thanks Max!

**Pull request merged**
