### PR TITLE
feat: deprecate 'KeepAlive::Until' globally

### PR DESCRIPTION
**Pull request by drHuangMHT**
## Description

Related: #3844

## Notes & open questions

Breaking change: `Swarm` no longer process `KeepAlive::Until` timeout and will be treated the same as `KeepAlive::Yes`
Can be quite buggy.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by drHuangMHT** [comment]
Test `libp2p-swarm` failed because default `OneshotHandlerConfig` has `keep_alive_timeout` of 10 seconds. When first-time polling returns `Pending` the handler won't be polled again, but the timer is set to 10 seconds after the first poll. The timer is not ready and the `keep_alive` flag is not set to `No`.

**Comment by thomaseizinger** [comment]
Thanks for working on this!

Instead of using timers, I'd actually like our protocols to not keep connections alive unless they are doing work on them. Thus, the way I'd like #3844 to be implemented is by doing https://github.com/libp2p/rust-libp2p/pull/3876 for each protocol.

Doing one PR per protocol would be great, as that allows us to bisect more easily in case we accidentally introduce a bug here.

Once all protocols are migrated away from `Until`, we can deprecate it and recommend our users to the same.

Does that make sense?

**Comment by drHuangMHT** [comment]
> Instead of using timers, I'd actually like our protocols to not keep connections alive unless they are doing work on them. Thus, the way I'd like #3844 to be implemented is by doing https://github.com/libp2p/rust-libp2p/pull/3876 for each protocol.

Sure. Keeping a timer around can be quite troublesome.

**Comment by drHuangMHT** [comment]
Close this as not planned.

**Pull request closed without merging**
