### PR TITLE
chore: refactor dcutr and gossipsub tests to use tokio instead

### PR DESCRIPTION
**Pull request by kamuik16**
## Description

 ref #4449 

Refactored dcutr and gossipsub tests to use `tokio` instead of `async-std`.

### CODE REVIEW

**Comment by kamuik16** [comment]
I don't think CI failure is related to my changes. Need someone else's eyes on it.

**Comment by kamuik16** [comment]
> I don't think CI failure is related to my changes. Need someone else's eyes on it.

Passing now.

**Review by jxs — COMMENTED** [review]
Thanks for this! Looks good to me, but can we split this into two PR's for each behaviour?

**Comment by kamuik16** [comment]
> Thanks for this! Looks good to me, but can we split this into two PR's for each behaviour?

Hey, for this one do you mind keeping this one, I'll make sure to make separate PRs for each behavior from next time.

**Comment by kamuik16** [comment]
> > Thanks for this! Looks good to me, but can we split this into two PR's for each behaviour?
> 
> Hey, for this one do you mind keeping this one, I'll make sure to make separate PRs for each behavior from next time.

re: @jxs

**Comment by kamuik16** [comment]
@jxs: squashed all of the commits into one, and only cargo deny is failing, so can we merge this?

**Review by jxs — DISMISSED** [review]
LGTM

**Comment by kamuik16** [comment]
> LGTM

aah, the mergify couldn't merge becuase the branch wasn't updated so I merge the master into this one. Seems like because of it the approval was dismissed, could you approve it once again?

**Comment by jxs** [comment]
> > LGTM
> 
> aah, the mergify couldn't merge becuase the branch wasn't updated so I merge the master into this one. Seems like because of it the approval was dismissed, could you approve it once again?

no need to do that, mergify does it automatically :)

**Review by jxs — APPROVED** [review]

**Pull request merged**
