### PR TITLE
*: Prepare v0.45.0

### PR DESCRIPTION
**Pull request by mxinden**
# Description

I would like to release `v0.45.0` soonish.

Outstanding things to be included:

- [x] https://github.com/libp2p/rust-libp2p/issues/2651

Please comment below to propose pull requests you would like to see included.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Nothing pressing to include from my end.

**Comment by mxinden** [comment]
I have been testing this code on kademlia-exporter.max-inden.de/ and a rust-libp2p based IPFS bootstrap node. Thus far, no anomalies.

I would very much appreciate further testing by others. Most notable changes that might reveal subtle bugs in downstream code:

- https://github.com/libp2p/rust-libp2p/pull/2626
- https://github.com/libp2p/rust-libp2p/pull/2627
- https://github.com/libp2p/rust-libp2p/pull/2638

//CC @divagant-martian @AgeManning @tomaka @kpp

**Comment by mxinden** [comment]
Published and tagged the following releases:

- libp2p-autonat-0.4.0
- libp2p-core-0.33.0
- libp2p-dcutr-0.3.0
- libp2p-deflate-0.33.0
- libp2p-dns-0.33.0
- libp2p-floodsub-0.36.0
- libp2p-gossipsub-0.38.0
- libp2p-identify-0.36.0
- libp2p-kad-0.37.0
- libp2p-mdns-0.37.0
- libp2p-metrics-0.6.0
- libp2p-mplex-0.33.0
- libp2p-noise-0.36.0
- libp2p-ping-0.36.0
- libp2p-plaintext-0.33.0
- libp2p-relay-0.9.0
- libp2p-rendezvous-0.6.0
- libp2p-request-response-0.18.0
- libp2p-swarm-0.36.0
- libp2p-swarm-derive-0.27.2
- libp2p-tcp-0.33.0
- libp2p-wasm-ext-0.33.0
- libp2p-websocket-0.35.0
- libp2p-yamux-0.37.0
- prost-codec-0.1.0
- rw-stream-sink-0.3.0
- v0.45.0

**Comment by geotro** [comment]
Merge @kpp's good stuff plzplzplz ;)

**Pull request merged**
