### PR TITLE
chore(quic): prepare v0.9.0-alpha

### PR DESCRIPTION
**Pull request by mxinden**
## Notes & open questions

@kpp @thomaseizinger any objections?

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by dariusc93** [comment]
I am excited to see how this performs compared to the previous implementation, although shouldnt it be `0.9.0-alpha.0` instead?

**Comment by thomaseizinger** [comment]
> I am excited to see how this performs compared to the previous implementation, although shouldnt it be `0.9.0-alpha.0` instead?

See https://github.com/libp2p/rust-libp2p/blob/master/docs/release.md#dealing-with-alphas.

**Comment by thomaseizinger** [comment]
> > I am excited to see how this performs compared to the previous implementation, although shouldnt it be `0.9.0-alpha.0` instead?
> 
> See [`master`/docs/release.md#dealing-with-alphas](https://github.com/libp2p/rust-libp2p/blob/master/docs/release.md?rgh-link-date=2023-07-29T15%3A54%3A49Z#dealing-with-alphas).

One could argue that this change is non-breaking but given that it is essentially a re-write, I think it is better to release it as a breaking change to make the update an explicit yet effortless action.

**Comment by thomaseizinger** [comment]
No objection. What is the plan forward for removing the alpha status of QUIC?

**Comment by mxinden** [comment]
> I am excited to see how this performs compared to the previous implementation, although shouldnt it be `0.9.0-alpha.0` instead?

Numbers on https://observablehq.com/@libp2p-workspace/performance-dashboard look very promising (see `rust-libp2p-quinn`) @dariusc93.

**Comment by mxinden** [comment]
> What is the plan forward for removing the alpha status of QUIC?

We have multiple outstanding bugs:

- https://github.com/libp2p/rust-libp2p/issues/4259
- https://github.com/libp2p/rust-libp2p/issues/4165
- https://github.com/libp2p/rust-libp2p/issues/3419

I would have to give the above bugs a bit more thought. Though I am leaning towards releasing `v0.9.0` (without `-alpha`), in case no major bugs are found in `v0.9.0-alpha`.

**Comment by mxinden** [comment]
[Tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-quic-v0.9.0-alpha) and [published](https://crates.io/crates/libp2p-quic/0.9.0-alpha).

**Pull request merged**
