### PR TITLE
refactor(kad): split `debug_assert`

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@stormshield-frb Would you mind testing bootstrapping with this branch?

**Comment by stormshield-frb** [comment]
Hi @thomaseizinger. We don't really need to test this because this is our current workaround: 

```rust
if let Err(push_err) = result {
    match push_err {
        futures_bounded::PushError::BeyondCapacity(_) => {
            debug_assert!(false, "Expected to not create more streams than allowed");
        }
        futures_bounded::PushError::Replaced(_) => {
            tracing::warn!(
                "Query {:?} already has a pending stream request, replaced existing",
                id
            );
        }
    }
}
```

So we can confirm that we indeed go through the `PushError::Replaced` case. For the current time being, we did not observe any noticeable side effects.

However, since a future is replaced (ie. dropped), the `receiver` owned by the future is dropped :

https://github.com/libp2p/rust-libp2p/blob/543408bec68c6d8fdef352a1a2a41994af9a4ca3/protocols/kad/src/handler.rs#L556-L558

so, when the `sender` try to send the result of the new stream opening, the `.send()` fails (which is silently ignored) :

https://github.com/libp2p/rust-libp2p/blob/543408bec68c6d8fdef352a1a2a41994af9a4ca3/protocols/kad/src/handler.rs#L792-L794

On the other end, it is legitimate to have several time the same `QueryId` in the same `Connection` at the "same" time? (in our case it is a `QueryId` from a bootstrap triggering `HandlerIn::FindNodeReq`).

Moreover, when the `try_push` returns `PushError::Replaced`, the replaced future is, in the end, stopped and dropped. Is it not a problem?

**Comment by stormshield-frb** [comment]
By the way, we noticed the same assumption (that an error is always `PushError::BeyondCapacity`) multiple times in a more recent work in `protocols/relay/src/priv_client/handler.rs`

https://github.com/libp2p/rust-libp2p/blob/543408bec68c6d8fdef352a1a2a41994af9a4ca3/protocols/relay/src/priv_client/handler.rs#L224-L226

**Comment by thomaseizinger** [comment]
> On the other end, it is legitimate to have several time the same `QueryId` in the same `Connection` at the "same" time? (in our case it is a `QueryId` from a bootstrap triggering `HandlerIn::FindNodeReq`).

Ah this is explains it! Well, in this case, we should probably just move from `FuturesMap` to `FuturesSet`. I didn't know that `QueryId`s would actually not be unique.

cc @mxinden Was this on purpose? I think this is something that we should definitely document or change. It isn't intuitive at all!

This also means the current logic is completely broken because we will abort a lot of outgoing requests. I'll see to send a fix later!

**Pull request closed without merging**
