### PR TITLE
Add back the relay

### LINKED ISSUE #725: Add back the relay
#723 removed the implementation of `relay` which was outdated and unusable.
It should be put back.

### PR DESCRIPTION
**Pull request by tomaka**
Fix #725 

Non-working work-in-progress.
Adds back the relay protocol.

Continuing this PR is basically blocked on resolving the questions in #725.

### CODE REVIEW

**Comment by dingxiangfei2009** [comment]
Hello, @tomaka. I wonder if you still have interest in the work to reinstate support for circuit relay at the moment. Would you mind that I take this partial work and try to complete it? :smile:

**Comment by tomaka** [comment]
Hi, sure!
From what I remember, the work on this PR wasn't really being blocked on anything.
You might encounter some of the challenges described in #725.

If you work on this, be aware that at the moment I might unfortunately not necessarily have the time to answer questions about difficulties that you might face.

**Comment by mxinden** [comment]
A rudimentary merge of current master that compiles can be found here: https://github.com/mxinden/rust-libp2p/commit/ccbc906a2a04da920bcbd82440d72d82bc34ff53

**Comment by mxinden** [comment]
Closing here in favor of https://github.com/libp2p/rust-libp2p/pull/1838.

**Pull request closed without merging**
