### PR TITLE
fix(examples/file-sharing): set Kademlia `Mode::Server`

### PR DESCRIPTION
**Pull request by mxinden**
## Description

Explicitly set `libp2p-kad` `Kademlia::set_mode` to `Mode::Server` to reduce complexity of example, i.e. not having to explicitly set external addresses.

## Notes & open questions

Similar to https://github.com/libp2p/rust-libp2p/issues/4194.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
> Explicitly set `libp2p-kad` `Kademlia::set_mode` to `Mode::Server` to reduce complexity of example, i.e. not having to explicitly set external addresses.

Is that a good thing? Would it be better if we teach users to "correctly" configure their `Swarm` with an external address?

**Comment by mxinden** [comment]
In my eyes, explicitly setting `Mode::Server` reduces complexity. This example showcases how to use libp2p in a larger application architecture. I don't think users should worry about Kademlia details like requiring an external address. In addition, I expect users to run this locally. Setting a `localhost` address as an external address would be confusing to me.

Does the above change your position here @thomaseizinger?

**Comment by thomaseizinger** [comment]
> In my eyes, explicitly setting `Mode::Server` reduces complexity. This example showcases how to use libp2p in a larger application architecture. I don't think users should worry about Kademlia details like requiring an external address. In addition, I expect users to run this locally. Setting a `localhost` address as an external address would be confusing to me.
> 
> Does the above change your position here @thomaseizinger?

Sounds good to me!

**Comment by mxinden** [comment]
Mind approving @thomaseizinger?

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
@mergifyio refresh

**Pull request merged**
