### PR TITLE
Add helpers for easier Transports creation

### LINKED ISSUE #735: Add helpers to create a transport with secio and mplex/yamux
Most people just want secio, mplex and yamux. We should add a helper that easily creates a transport like that.

### PR DESCRIPTION
**Pull request by tomaka**
Fix #735 

Also makes `CommonTransport` private.
I tried to remove `CommonTransport` in favour of a `build_tcp_ws()` method, but I got compilation errors.

It would be nice to eventually remove all these `Send`/`Sync` requirements, but I'm not sure how.

### CODE REVIEW

**Comment by daogangtang** [comment]
libp2p::build_development_transport(local_key); 

Why use this function name, seems casual.

**Comment by tomaka** [comment]
> seems casual.

What do you mean by casual?

**Comment by daogangtang** [comment]
> > seems casual.
> 
> What do you mean by casual?

if we have a API named build_development_transport, do we have a product version: build_product_transport?

**Comment by tomaka** [comment]
I'm going to merge this. Let me know if that's not fine.

**Comment by daogangtang** [comment]
> The production version would be `build_tcp_ws_secio_mplex_yamux()`.
> The difference is that `build_development_transport()` will get support for additional new protocols, while others are specific to a specific set of protocols and will not change.

OK.

**Pull request merged**
