### PR TITLE
Return the correct number of remaining bootstrap requests.

### PR DESCRIPTION
**Pull request by rubdos**
As per the discussion on #2121 

I can confirm that the bootstrap process seems to go a lot better now :-)

@izolyomi, I included you as `Co-authored-by` in the commit, but don't have an email address for it. Let me know if you want a change there.

### CODE REVIEW

**Comment by izolyomi** [comment]
>I included you as `Co-authored-by` in the commit, but don't have an email address for it. Let me know if you want a change there.

Thanks for the nice gesture. 😃 
Feel free to keep or remove me as co-author, just merge this PR as you see fit regarding your usual workflow.

**Comment by mxinden** [comment]
Thanks @rubdos. Very much appreciated.

Would you mind including the diff below to prevent future regressions?

```diff
diff --git a/protocols/kad/src/behaviour/test.rs b/protocols/kad/src/behaviour/test.rs
index 7f73c1d8..f22b4b65 100644
--- a/protocols/kad/src/behaviour/test.rs
+++ b/protocols/kad/src/behaviour/test.rs
@@ -196,6 +196,10 @@ fn bootstrap() {
                                 }
                                 first = false;
                                 if ok.num_remaining == 0 {
+                                    assert_eq!(
+                                        swarm.behaviour_mut().queries.size(), 0,
+                                        "Expect no remaining queries when `num_remaining` is zero.",
+                                    );
                                     let mut known = HashSet::new();
                                     for b in swarm.behaviour_mut().kbuckets.iter() {
                                         for e in b.iter() {
```

**Comment by mxinden** [comment]
And please also add an entry to the changelog:

```diff
diff --git a/protocols/kad/CHANGELOG.md b/protocols/kad/CHANGELOG.md
index db0b9f0d..18c03d53 100644
--- a/protocols/kad/CHANGELOG.md
+++ b/protocols/kad/CHANGELOG.md
@@ -13,8 +13,11 @@
 
 - Remove false `debug_assert` on `connected_peers` (see [PR 2120]).
 
+- Return correct number of remaining bootstrap requests (see [PR 2125]).
+
 [PR 2087]: https://github.com/libp2p/rust-libp2p/pull/2087
 [PR 2120]: https://github.com/libp2p/rust-libp2p/pull/2120
+[PR 2125]: https://github.com/libp2p/rust-libp2p/pull/2125
 
 # 0.30.0 [2021-04-13]
```

**Comment by rubdos** [comment]
Done, @mxinden. Thanks for the quick replies.

Here's to contributing some more in the near future :-)

**Review by mxinden — APPROVED** [review]
> Here's to contributing some more in the near future :-)

:rocket: always welcome. Let me know if you need any help.

**Pull request merged**
