### PR TITLE
[WIP] gossipsub: an extensible baseline pubsub protocol

### PR DESCRIPTION
**Pull request by jamesray1**
There is a spec [here](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub). Previously I was implementing episub in #291, however that extends on gossipsub, so it's better to implement gossipsub first. It took a while to really get into development as I was reading through relevant specs, code, learnt Go, tokio, protobuf, and how to best extend on floodsub in terms of code structure e.g. with nested structs, traits and copying and pasting private stuff.

Outdated (comments have changed): for a comparison of  rpc_proto.rs and rpc.proto between gossipsub and floodsub, see https://github.com/libp2p/rust-libp2p/pull/428.

Closes https://github.com/libp2p/rust-libp2p/pull/421, this renames the branch name for brevity as prior versions should not need to be revisited.

```
// Importing floodsub isn't sufficient as there is a lot of private stuff.
// For this reason it seems that floodsub and gossipsub need to be in the same
// file. It seems like you need to copy and paste pretty much everything from floodsub,
// as public parts contain private parts. 
// 
// Going forward, the floodsub crate could also be maintained in this crate,
// to avoid duplication of maintaining floodsub in this crate and in the
// floodsub crate.
```

### CODE REVIEW

**Comment by jamesray1** [comment]
Due to #568, floodsub will need to be made compatible before continuing work on gossipsub, which extends on floodsub,

**Comment by tomaka** [comment]
Floodsub has been upgraded for the new design.

**Comment by jamesray1** [comment]
Still trying to catch up with the changes. Details at https://docs.google.com/spreadsheets/d/1Fv8XqLkMjdBkGPkVWfJulJU-5Qv6TSUR4oD5uKSEHW0/edit#gid=456490482.

**Comment by jamesray1** [comment]
See #767.

**Pull request closed without merging**
