### PR TITLE
Use unsigned-varint crate.

### PR DESCRIPTION
**Pull request by twittner**
https://github.com/paritytech/unsigned-varint

### CODE REVIEW

**Comment by gnunicorn** [comment]
needs a rebase.

**Comment by twittner** [comment]
> Just a little uneasy with having a git = in the Cargo.toml without any version reference. Maybe add one (if possible with git) or a tag/commit so it doesn't break in the future for unknown reasons?

I do not expect this particular dependency to change much. In general I would like to avoid pinning to specific commits as it may result in frequent version bumps. Instead we could  publish `unsigned-varint` to `crates.io` or have a stable branch in `unsigned-varint` (e.g. `v1`) which receives only bugfixes.

**Comment by twittner** [comment]
I have opened https://github.com/paritytech/unsigned-varint/pull/1 to prepare it for publishing.

**Comment by tomaka** [comment]
I suggest we test this in polkadot before merging.
Not that the network is super robust yet, but at least we will notice if something is very wrong in this code.

**Comment by twittner** [comment]
@tomaka: Good idea! Related: https://github.com/paritytech/unsigned-varint/issues/2

**Pull request merged**
