### PR TITLE
Identify transport with PeerId exchange

### PR DESCRIPTION
**Pull request by echupriyanov**
Initial implementation

Related to #460 and #443 

@tomaka Can you, please, take a look. Does this make any sense?

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks for the work!

I think that the protocols should be unidirectional, like `identify` is already. What I mean is that you should open a substream, then the remote sends back the information and closes the substream. I think it's more elegant this way than if we have the two nodes both send their infos.

Other than that, I'm still conflicted about where exactly to split the protocols.

**Comment by echupriyanov** [comment]
Maybe we can have both variants? What I did is quite simple transport with public keys exchange during connection establishment. So it can be used transparently in the chain of transport upgrades.

On the other hand, there will be `Identify` protocol, which will function as you describe, providing more detailed node info.

What do you think?

**Comment by tomaka** [comment]
> Maybe we can have both variants?

I think we shouldn't require nodes to support even more additional protocols if they don't have to.

I think that in order to solve #460 we should only create a transport that opens an identify substream (as in, the protocol that already exists and is deployed in IPFS) in order to retrieve the public key.

The main reason why I wanted to design new protocols (in #443) is to make it possible to communicate arbitrary information, and to make it possible to split the observed address from the rest.

If we design new protocols (#443), we can extend the new transport I'm talking about to support both the existing identify protocol and the new protocol.

**Comment by echupriyanov** [comment]
Obsolete now

**Pull request closed without merging**
