### PR TITLE
chore: move `libp2p` crate to a dedicated directory

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

Currently, our top-level `Cargo.toml` manifest represents a crate AND a workspace. This causes surprising behaviour (e.g. #2949) where we need to explicitly pass `--workpace` to every command to run it on the entire workspace and not just the meta crate.

My moving the meta crate into its own directory, the root manifest file is a virtual manifest only and thus, every `cargo` command will automatically default to running on the entire workspace.

On top of this, I personally find it easier to understand if workspace and crate manifests are not mixed.

## Notes

This is https://github.com/libp2p/rust-libp2p/pull/3012 but started fresh because it had so many conflicts. Also, I am not renaming any crates in here.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Change looks good to me. Feel free to merge whenever you see fit @thomaseizinger.

You could consider adding the final squash commit to https://github.com/libp2p/rust-libp2p/blob/master/.git-blame-ignore-revs.

**Comment by thomaseizinger** [comment]
> You could consider adding the final squash commit to https://github.com/libp2p/rust-libp2p/blob/master/.git-blame-ignore-revs.

That is a good idea, I'll send a follow-up once this is merged.

**Comment by thomaseizinger** [comment]
Getting some very strange compile errors here. Somehow, cargo seems to treat these packages differently, now that the root manifest is a virtual workspace. I'll keep digging but that is a good validation to me that we should definitely move into this direction. Who knows how that might affect users.

**Comment by thomaseizinger** [comment]
> Getting some very strange compile errors here. Somehow, cargo seems to treat these packages differently, now that the root manifest is a virtual workspace. I'll keep digging but that is a good validation to me that we should definitely move into this direction. Who knows how that might affect users.

No luck so far. Somehow, `ring` gets pulled in as a dependency as part of `snow` through the `default-resolver` feature but only if I compile for `wasm32-unknown-emscripten` and `wasm32-wasi`. At least that is what I could gather from the `cargo tree` output. Weirdly, looking at `snow`'s source code, I cannot see how `ring` is meant to be a dependency. I am starting to think that this is a bug in `cargo`.

**Comment by thomaseizinger** [comment]
OMG, I think I found it. What a mess :joy: 

So previously, our root crate was an `edition = 2021` crate which implies version 2 of the dependency resolver. That one is necessary to correctly resolve target specific dependencies (don't ask me why I know that, way too many hours wasted prior to this PR already). Now that it is a virtual manifest, cargo needs to be explicitly told that we want `resolver = 2` in order to honor the `cfg` expressions within `libp2p-noise`'s `Cargo.toml`.

**Comment by thomaseizinger** [comment]
I opened an issue with `cargo`: https://github.com/rust-lang/cargo/issues/11811

**Pull request merged**
