### PR TITLE
feat(mergify): only queue PRs if they target master

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

This is useful for stacked PRs. One can apply the `send-it` label and wait for GitHub to retarget the PR to the actual base branch once the dependent PR merges.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
What about back-port pull requests?

**Comment by thomaseizinger** [comment]
> What about back-port pull requests?

Our CI is unlikely to completely pass on backport PRs because we for example do not pin the version of the interop-tests action and in previous releases, we also didn't pin the version of clippy, causing newly introduced lints to break the build on backport PRs.

Additionally, we don't have branch protection rules enabled for older PRs (should we?) so mergify will merge any PR instantly that has the `send-it` label.

I think a more useful policy is to manually examine the CI result of a backport PR and merge once we consider it ready. You can always use the `@mergifyio queue` command to manually queue a PR. That will use the same logic of creating the commit message from the PR description as we do for PRs to master.

**Review by mxinden — APPROVED** [review]
Makes sense. Thanks

**Comment by thomaseizinger** [comment]
@mergifyio queue

**Pull request merged**
