### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by Thabokani**
## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — DISMISSED** [review]

**Review by thomaseizinger — DISMISSED** [review]

**Comment by drHuangMHT** [comment]
@thomaseizinger Stalled for `cargo deny` error

**Comment by drHuangMHT** [comment]
Are we not resolving dependency issue very soon? I'm seeing some MAJOR version bumps in `cargo deny` and recent tests kept failing. @thomaseizinger

**Comment by thomaseizinger** [comment]
> Are we not resolving dependency issue very soon? I'm seeing some MAJOR version bumps in `cargo deny` and recent tests kept failing. @thomaseizinger

Mergify is somehow broken and I don't have the resources to fix it unfortunately. Help is much appreciated!

Perphaps we should also move to GitHub's merge queue.

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
may it be that it's just flaky?

**Pull request merged**
