### PR TITLE
fix(changelog): Make release heading levels consistent

### LINKED ISSUE #3531: CHANGELOG.md enhancements
## Description
When looking at https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md with fresh eyes, a few minor things stood out:

1. We don't have a TOC at the top.  I assume that's because we're relying on one to use tooling from their viewer:
image
2. Heading levels changed at v45.0
image
3. We stopped including a date in v44.0.  (I assume that's intentional to to make it quicker for manually creating an anchor link to a specific version.

## Motivation
This isn't critical.  Feel free to resolve.  I'm just posting in case this wasn't intentional or we do further adjustments to changelog.md in the future.

I do think we should make sure we do a good job of highlighting why a certain release matters in https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md#libp2p-facade-crate

## Are you planning to do it yourself in a pull request?
No

### PR DESCRIPTION
**Pull request by mxinden**
## Description

See `##` for release headings everywhere. This is consistent with markdown conventions of one `#` per document and in line with https://keepachangelog.com/.

See report in https://github.com/libp2p/rust-libp2p/issues/3531.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I think that is technically not valid markdown as a document should only have one top-level heading.

**Comment by mxinden** [comment]
Note @thomaseizinger that we do this in all changelog files. Happy to change it across the repository. Just want to check-in before I do so.

**Comment by mxinden** [comment]
Friendly ping @thomaseizinger.

Will resolve the merge conflicts once decision is made.

**Comment by thomaseizinger** [comment]
> Friendly ping @thomaseizinger.
> 
> Will resolve the merge conflicts once decision is made.

Sorry missed this. Yes I'd appreciate if we used consistent levels across all files.

**Comment by mxinden** [comment]
@thomaseizinger mind taking a look?

As an aside, quite a lot of releases by now :tada:

**Comment by thomaseizinger** [comment]
> @thomaseizinger mind taking a look?

I didn't go through all documents manually but I spotchecked some and they seem to render correctly :)

Also can't find any L1 headings via the search.

**Review by thomaseizinger — APPROVED** [review]

**Pull request merged**
