### PR TITLE
deps: Promote tracing to workspace dependency

### PR DESCRIPTION
**Pull request by drHuangMHT**
## Description

Promote tracing to workspace dependency to make mananging depencencies easier.

## Notes & open questions

Related issue: #5230

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by drHuangMHT** [comment]
Is a changelog entry required in this case?

**Comment by jxs** [comment]
> Is a changelog entry required in this case?

not if you specify it as `chore, docs` etc, see:
https://github.com/libp2p/rust-libp2p/blob/3644879956b6ab93b8d23553a33e8fdb838f576f/.github/workflows/ci.yml#L93-L98

can you push again to re-trigger the CI @drHuangMHT 
thanks!

**Comment by drHuangMHT** [comment]
@jxs Ready for review.

**Review by jxs — APPROVED** [review]
LGTM thanks for this! :rocket:

**Pull request merged**
