### PR TITLE
deps(quic): upgrade quinn to address RUSTSEC-2023-0063

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

https://rustsec.org/advisories/RUSTSEC-2023-0063 was recently published, this address it.

## Notes & open questions

na

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by divagant-martian** [comment]
@mxinden you might want to include in #4537

**Comment by thomaseizinger** [comment]
Thanks but if it is a patch-release, then users can upgrade that themselves!

We should update our lockfile of course but we don't need to mention that in the changelog :)

**Comment by divagant-martian** [comment]
is your specific suggestion to simply remove the changelog @thomaseizinger?

**Comment by thomaseizinger** [comment]
> is your specific suggestion to simply remove the changelog @thomaseizinger?

Yes please! :)

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
> @mxinden you might want to include in #4537

Just to be clear: Releasing this PR has no effect for our users because they have their own lockfile.

**Comment by divagant-martian** [comment]
not sure if you noticed but #4537 has workflows failing because of this, thus it needs to be included, not referring to users, so yeah. we are on the same page :)

**Comment by thomaseizinger** [comment]
> not sure if you noticed but #4537 has workflows failing because of this, thus it needs to be included, not referring to users, so yeah. we are on the same page :)

Ah yes, thank you for that! We don't require those for merging because there isn't always an immediate solution available but it is good to be fixed, thank you! :)

**Pull request merged**
