### PR TITLE
chore(*): Run rustfmt 1.7.0 and clippy 0.1.76

### PR DESCRIPTION
**Pull request by umgefahren**
## Description

Ran cargo fmt and cargo clippy --fix with the respective new nightly versions.

## Notes & open questions

While I have no issues with the fixes introduced by clippy, I have issues with the new rustfmt version.

As you can see the changes are quite severe and the change in style is stronger then in previous releases.

We should be careful when merging into master, because every PR that doesn't use the nightly compiler and runs the format will probably have a merge conflict. But we probably have to do it eventually.

An upside of the changes, at least from my POV is that changes are now spread over more lines, which could be beneficial for merge conflict resolution.

I would suggest we keep this PR open and I update it regularly with the nightly versions of rustfmt. It's a lot of work to merge that probably, so I'd suggest we merge the version that will be released eventually.

## Change checklist

- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by umgefahren** [comment]
This single PR is so massive, it would probably be my biggest contribution (in the stats) by far, which is... interesting.

**Comment by thomaseizinger** [comment]
> I have issues with the new rustfmt version.

Me too and I am somewhat surprised that the Rust team would ship that!

> While I have no issues with the fixes introduced by clippy

Can you extract that into a separate PR (and bump the nightly clippy version in CI). We will update to clippy once 1.75 is stable so we might as well fix those lints early.

**Comment by umgefahren** [comment]
> > I have issues with the new rustfmt version.
> 
> Me too and I am somewhat surprised that the Rust team would ship that!

Should we open an issue with them, if there isn't one already?

> > While I have no issues with the fixes introduced by clippy
> 
> Can you extract that into a separate PR (and bump the nightly clippy version in CI). We will update to clippy once 1.75 is stable so we might as well fix those lints early.

Will do, some of the remaining lints need manual fixing though and will introduce breaking changes in public APIs.

**Comment by thomaseizinger** [comment]
> > > I have issues with the new rustfmt version.
> > 
> > Me too and I am somewhat surprised that the Rust team would ship that!
> 
> Should we open an issue with them, if there isn't one already?

I think it may come as part of the next edition which would allow for such changes to be made AFAIK.

> > > I have issues with the new rustfmt version.
> > 
> > 
> > Me too and I am somewhat surprised that the Rust team would ship that!
> 
> Should we open an issue with them, if there isn't one already?
> 
> > > While I have no issues with the fixes introduced by clippy
> > 
> > 
> > Can you extract that into a separate PR (and bump the nightly clippy version in CI). We will update to clippy once 1.75 is stable so we might as well fix those lints early.
> 
> Will do, some of the remaining lints need manual fixing though and will introduce breaking changes in public APIs.

Happy to merge the easy ones first and hold off on all the breaking ones until we do another release.

**Comment by jxs** [comment]
closing as stale

**Pull request closed without merging**
