### PR TITLE
Add regex feature for gossipsub

### LINKED ISSUE #2055: `RegexSubscriptionFilter` hidden behind undefined feature
Hello,

I'm trying to use the `libp2p::gossipsub::subscription_filter::RegexSubscriptionFilter`, but it's hidden because of the conditional compilation in
 https://github.com/libp2p/rust-libp2p/blob/29d969be340b610e19bf05661b731883f25e6821/protocols/gossipsub/src/subscription_filter.rs#L203. The `"regex-filter"` feature is not defined anywhere, so there's seems to be no way to switch it on.

### PR DESCRIPTION
**Pull request by tzemanovic**
closes #2055

### CODE REVIEW

**Comment by AgeManning** [comment]
It might make more sense to just remove the condition compilation inside gossipsub such that any libp2p implementation that compiles with gossipsub also gets regex by default. 

This saves the crate-level feature flag that also enables gossipsub and regex. 

What do you think?

**Comment by mxinden** [comment]
> What do you think?

Though this question is likely not addressed to me, I am in favor of @AgeManning's suggestion. @tzemanovic do you want to update the pull request?

**Comment by tzemanovic** [comment]
sounds good, will do!

**Comment by mxinden** [comment]
@tzemanovic can you apply the diff below? I can then cut a patch release of `libp2p-gossipsub` later today.

``` diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 62705acc..629bc522 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -45,6 +45,7 @@
 
 - Update individual crates.
     - `libp2p-core`
+    - `libp2p-gossipsub`
 
 ## Version 0.37.1 [2021-04-14]
 
diff --git a/Cargo.toml b/Cargo.toml
index acb1ab8d..1b1a5ceb 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -66,7 +66,7 @@ futures = "0.3.1"
 lazy_static = "1.2"
 libp2p-core = { version = "0.28.3", path = "core",  default-features = false }
 libp2p-floodsub = { version = "0.29.0", path = "protocols/floodsub", optional = true }
-libp2p-gossipsub = { version = "0.30.0", path = "./protocols/gossipsub", optional = true }
+libp2p-gossipsub = { version = "0.30.1", path = "./protocols/gossipsub", optional = true }
 libp2p-identify = { version = "0.29.0", path = "protocols/identify", optional = true }
 libp2p-kad = { version = "0.30.0", path = "protocols/kad", optional = true }
 libp2p-mplex = { version = "0.28.0", path = "muxers/mplex", optional = true }
diff --git a/protocols/gossipsub/CHANGELOG.md b/protocols/gossipsub/CHANGELOG.md
index 9d916961..7bc1f9aa 100644
--- a/protocols/gossipsub/CHANGELOG.md
+++ b/protocols/gossipsub/CHANGELOG.md
@@ -1,3 +1,8 @@
+# 0.30.1 [2021-04-27]
+
+- Remove `regex-filter` feature flag thus always enabling `regex::RegexSubscriptionFilter` [PR
+  2056](https://github.com/libp2p/rust-libp2p/pull/2056).
+
 # 0.30.0 [2021-04-13]
 
 - Update `libp2p-swarm`.
diff --git a/protocols/gossipsub/Cargo.toml b/protocols/gossipsub/Cargo.toml
index eaa21894..a0ecc7e3 100644
--- a/protocols/gossipsub/Cargo.toml
+++ b/protocols/gossipsub/Cargo.toml
@@ -2,7 +2,7 @@
 name = "libp2p-gossipsub"
 edition = "2018"
 description = "Gossipsub protocol for libp2p"
-version = "0.30.0"
+version = "0.30.1"
 authors = ["Age Manning <Age@AgeManning.com>"]
 license = "MIT"
 repository = "https://github.com/libp2p/rust-libp2p"
```

**Comment by tzemanovic** [comment]
@mxinden done, thanks!

**Review by mxinden — APPROVED** [review]

**Comment by mxinden** [comment]
Thanks @tzemanovic.

`libp2p-gossipsub` `v0.30.1` [tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-gossipsub-0.30.1) and [published](https://crates.io/crates/libp2p-gossipsub/0.30.1).

**Pull request merged**
