### PR TITLE
refactor(relay): introduce `Handler::new` functions

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Notes

Will reduce the diff in https://github.com/libp2p/rust-libp2p/pull/3254.
Draft until https://github.com/libp2p/rust-libp2p/pull/3318 is merged.
2nd attempt of https://github.com/libp2p/rust-libp2p/pull/3326.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
This is ready for review despite being draft. Only #3318 needs to merge first.

**Review by jxs — APPROVED** [review]
LGTM

**Comment by thomaseizinger** [comment]
@mergifyio refresh

**Comment by thomaseizinger** [comment]
@mergifyio queue

**Pull request merged**
