### PR TITLE
docs: enhance  code documentation

### PR DESCRIPTION
**Pull request by DoTheBestToGetTheBest**
## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by dariusc93** [comment]
It looks like this isnt a refactoring but just commenting on bits of code for documentation. If this is the case might be worth changing the PR title to reflect that :)

**Comment by DoTheBestToGetTheBest** [comment]
> It looks like this isnt a refactoring but just commenting on bits of code for documentation. If this is the case might be worth changing the PR title to reflect that :)

thanks for your reply, does it look better for you ?

**Review by jxs — DISMISSED** [review]
LGTM thanks for this!

**Comment by drHuangMHT** [comment]
Stalled PR @jxs.

**Comment by DoTheBestToGetTheBest** [comment]
not sure i understand what's the problem, should i do anything please?

**Comment by drHuangMHT** [comment]
Ping @jxs you forgot to re-approve the changes after new commits.

**Review by jxs — DISMISSED** [review]

**Comment by jxs** [comment]
@DoTheBestToGetTheBest can you `cargo fmt`?

**Comment by drHuangMHT** [comment]
um I think you need to approve the change *after* not before commit?

**Comment by jxs** [comment]
> um I think you need to approve the change _after_ not before commit?

yeah, I only noticed later that the `rustfmt` job was failing

**Comment by drHuangMHT** [comment]
Friendly ping @DoTheBestToGetTheBest Got a minute?

**Review by jxs — APPROVED** [review]

**Pull request merged**
