### PR TITLE
fix(misc/server): add repository URL to Cargo.toml

### PR DESCRIPTION
**Pull request by mxinden**
## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
Required for `v0.52.3` release https://github.com/libp2p/rust-libp2p/pull/4387.

**Comment by thomaseizinger** [comment]
Would this be caught by CI if we add a DRY release step for each crate?

**Comment by mxinden** [comment]
I would guess so. Though given that we don't add new crates very often and given that these pull requests are not a lot of work, is it worth the effort?

**Comment by thomaseizinger** [comment]
> I would guess so. Though given that we don't add new crates very often and given that these pull requests are not a lot of work, is it worth the effort?

Yeah that is fair :)

We might need some more CI once we add some form of automated publishing.

**Pull request merged**
