### PR TITLE
chore: prepare non-breaking releases

### PR DESCRIPTION
**Pull request by mxinden**
## Description

Crates to be released:

- core
- misc/futures-bounded
- misc/server
- misc/webrtc-utils
- protocols/kad
- protocols/ping
- protocols/upnp
- swarm
- transports/webrtc-websys
- transports/webrtc

## Notes & open questions

@jxs given https://github.com/libp2p/rust-libp2p/pull/4156/#issuecomment-1727777769

@mcamou given https://github.com/libp2p/rust-libp2p/pull/4467 and https://github.com/libp2p/rust-libp2p/pull/4466

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by jxs** [comment]
Thanks for this Max! https://github.com/libp2p/rust-libp2p/pull/4530 is also included

**Review by jxs — APPROVED** [review]

**Review by thomaseizinger — APPROVED** [review]
Yes, sounds good to me :)

I think we might want to do a few more point releases before the breaking one but there is no need to delay these further.

**Comment by mxinden** [comment]
> I think we might want to do a few more point releases before the breaking one

Got a particular non-breaking change in mind that you would like to release before tackling https://github.com/libp2p/rust-libp2p/milestone/7 @thomaseizinger?

**Comment by mxinden** [comment]
Published and tagged the following crates:

- futures-bounded-v0.1.0
- libp2p-core-v0.40.1
- libp2p-kad-v0.44.5
- libp2p-ping-v0.43.1
- libp2p-server-v0.12.3
- libp2p-swarm-v0.43.4
- libp2p-upnp-v0.1.0
- libp2p-webrtc-utils-v0.1.0
- libp2p-webrtc-v0.6.1-alpha
- libp2p-webrtc-websys-v0.1.0-alpha

**Comment by thomaseizinger** [comment]
> > I think we might want to do a few more point releases before the breaking one
> 
> Got a particular non-breaking change in mind that you would like to release before tackling https://github.com/libp2p/rust-libp2p/milestone/7 @thomaseizinger?

Let me have a closer look but I just want to make sure we don't miss certain deprecations for example for the upcoming breaking features :)

**Comment by thomaseizinger** [comment]
> > I think we might want to do a few more point releases before the breaking one
> 
> Got a particular non-breaking change in mind that you would like to release before tackling [libp2p/rust-libp2p/milestone/7](https://github.com/libp2p/rust-libp2p/milestone/7) @thomaseizinger?

These are all ready-to-review, non-breaking changes that contain deprecations which would allow us to remove certain code sooner, i.e. with the next breaking release:

- https://github.com/libp2p/rust-libp2p/pull/4029
- https://github.com/libp2p/rust-libp2p/pull/4505
- https://github.com/libp2p/rust-libp2p/pull/4535
- https://github.com/libp2p/rust-libp2p/pull/4540
- https://github.com/libp2p/rust-libp2p/pull/4102

**Pull request merged**
