### PR TITLE
*: Prepare v0.47.0

### PR DESCRIPTION
**Pull request by mxinden**
# Description

I suggest to release `libp2p` `v0.47.0`. Anything folks would like to see included that is not yet in `master`?

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Not from my end :)

**Comment by elenaf9** [comment]
👍

**Review by elenaf9 — APPROVED** [review]

**Comment by mxinden** [comment]
Sorry, never meant to open this as a _work in progress_. Thanks for the input everyone!

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-autonat-0.6.0
- libp2p-core-0.35.0
- libp2p-dcutr-0.5.0
- libp2p-deflate-0.35.0
- libp2p-dns-0.35.0
- libp2p-floodsub-0.38.0
- libp2p-gossipsub-0.40.0
- libp2p-identify-0.38.0
- libp2p-kad-0.39.0
- libp2p-mdns-0.39.0
- libp2p-metrics-0.8.0
- libp2p-mplex-0.35.0
- libp2p-noise-0.38.0
- libp2p-ping-0.38.0
- libp2p-plaintext-0.35.0
- libp2p-relay-0.11.0
- libp2p-rendezvous-0.8.0
- libp2p-request-response-0.20.0
- libp2p-swarm-0.38.0
- libp2p-swarm-derive-0.29.0
- libp2p-tcp-0.35.0
- libp2p-uds-0.34.0
- libp2p-wasm-ext-0.35.0
- libp2p-websocket-0.37.0
- libp2p-yamux-0.39.0
- prost-codec-0.2.0
- v0.47.0

**Pull request merged**
