### PR TITLE
core/transport/memory: Return dialer address in Upgrade event

### PR DESCRIPTION
**Pull request by mxinden**
Previously a `Listener` would return its own address as the
`remote_addr` in the `ListenerEvent::Upgrade` event.

With this commit a `Listener` returns the dialer address as the
`remote_addr` in the `ListenerEvent::Upgrade` event. To do so a
`DialFuture` registers a port with the global `HUB` at construction
which is later on unregistered in the `Drop` implementation of the
dialer's `Chan`. The sending side of the `mpsc::channel` registered in
the `HUB` is dropped at `DialFuture` construction, thus one can not dial
the dialer port. This mimics the TCP transport behaviour preventing both
dialing and listening on the same TCP port.

Closes https://github.com/libp2p/rust-libp2p/issues/1721.

### CODE REVIEW

**Comment by mxinden** [comment]
> #1721 does not mention what problems the current behaviour causes. Is it simply that the ListenerEvent::Upgrade::remote_addr is the same for all connections with the memory transport?

That was my impression but maybe @tomaka has more information in that regard?

**Comment by tomaka** [comment]
I opened #1721 after looking at Substrate logs and realizing that the local address and send back address were the same.
I admit that I didn't think this through too much. I immediately assumed that it was wrong and opened an issue to not forget about this problem. But it is in the end not obvious than it is a problem.

**Comment by mxinden** [comment]
I think the behavior introduced in this pull request is at least more intuitive than the current behavior. Thus I am voting to merge this pull request. Objections?

**Comment by romanb** [comment]
Please don't forget to update the changelog, either before merging or after.

**Comment by mxinden** [comment]
> Please don't forget to update the changelog, either before merging or after.

Thanks for the reminder @romanb! It slipped my mind.

**Pull request merged**
