### PR TITLE
Fix swarm changelog entry

### PR DESCRIPTION
**Pull request by jxs**
# Description

to address the mismatch between the CHANGELOG.md entry and the released version introduced [here](https://github.com/libp2p/rust-libp2p/pull/2918/files#diff-a558b0475dbda10372de40bbd53ef14d5c225f949dad7a7e639fb50e2cac1d3e).

### CODE REVIEW

**Comment by thomaseizinger** [comment]
What happened to 0.40.0? 😁

**Comment by mxinden** [comment]
> What happened to 0.40.0? grin

https://github.com/libp2p/rust-libp2p/pull/2918 updated from `libp2p-swarm` `v0.39.1` to `v0.40.1` skipping `v0.40.0`.

https://github.com/libp2p/rust-libp2p/pull/2918/files#diff-fdc23b5a0f3396511dad7c86646eb81dafe04b4caf8789c0b3ce1892319fe041R6

**Review by mxinden — APPROVED** [review]
Thanks @jxs!

**Comment by thomaseizinger** [comment]
> > What happened to 0.40.0? grin
> 
> https://github.com/libp2p/rust-libp2p/pull/2918 updated from `libp2p-swarm` `v0.39.1` to `v0.40.1` skipping `v0.40.0`.
> 
> https://github.com/libp2p/rust-libp2p/pull/2918/files#diff-fdc23b5a0f3396511dad7c86646eb81dafe04b4caf8789c0b3ce1892319fe041R6

A good data point against manual version bumping! (And that I am bad at resolving merge conflicts 😂)

**Pull request merged**
