### PR TITLE
*: Prepare v0.42.0

### PR DESCRIPTION
**Pull request by mxinden**
As promised, I am proposing to cut a new release, namely `v0.42.0`.

Pull requests I would like to wait for:

- [x] https://github.com/libp2p/rust-libp2p/pull/2428
- [x] https://github.com/libp2p/rust-libp2p/pull/2443
- [x] https://github.com/libp2p/rust-libp2p/pull/2444

Any other blockers or things you would like to see included?

I would very much appreciate help testing this branch on production setups before the release.

- @AgeManning @divagant-martian would you mind running this branch on a lighthouse node?
- @kpp @tomaka  do you have some time to do a burn-in on Substrate / Polkadot?
- @thomaseizinger can you test this branch on the Comit network stack?
- @elenaf9 could you test whether things run smoothly on the iotledger stack.
- @ec2 got some time to run this against the Filecoin network via Forest?
- @rkuhn want to give this a spin via ipfs-embed?
- Any other folks running rust-libp2p in larger environments?

### CODE REVIEW

**Comment by rkuhn** [comment]
Sounds excellent @mxinden! Unfortunately I’m at a customer this week, will probably be exceptionally busy until Thursday evening, which will likely delay both 2428 and updating ipfs-embed.

**Comment by mxinden** [comment]
Any oddities showing up on production deployments? If not, I will continue with the release sometime later this week.

**Comment by AgeManning** [comment]
Seems to look fine from our end.

**Comment by mxinden** [comment]
Note that with https://github.com/libp2p/rust-libp2p/pull/2440/commits/c69ce3b78371b6f2e4838d64f3878f1de4a804e5 each entry in the main `CHANGELOG.md` links to the concrete version entry in the sub-crate `CHANGELOG.md`. That should make reviewing the changes included in this release a whole lot easier. @tomaka what do you think?

**Comment by mxinden** [comment]
Published and released the following crates:

- libp2p-autonat-0.1.0
- libp2p-core-0.31.0
- libp2p-deflate-0.31.0
- libp2p-dns-0.31.0
- libp2p-floodsub-0.33.0
- libp2p-gossipsub-0.35.0
- libp2p-identify-0.33.0
- libp2p-kad-0.34.0
- libp2p-mdns-0.34.0
- libp2p-metrics-0.3.0
- libp2p-mplex-0.31.0
- libp2p-noise-0.34.0
- libp2p-ping-0.33.0
- libp2p-plaintext-0.31.0
- libp2p-relay-0.6.0
- libp2p-rendezvous-0.3.0
- libp2p-request-response-0.15.0
- libp2p-swarm-0.33.0
- libp2p-swarm-derive-0.26.1
- libp2p-tcp-0.31.0
- libp2p-uds-0.31.0
- libp2p-wasm-ext-0.31.0
- libp2p-websocket-0.33.0
- libp2p-yamux-0.35.0
- multistream-select-0.11.0
- v0.42.0


Thank you all for the many contributions. And thanks @divagant-martian and @AgeManning for testing.

**Pull request merged**
