### PR TITLE
fix(kad): improve memory allocation when iterating over kbuckets

### LINKED ISSUE #5712: Huge increase in memory allocation
### Summary

We have a server dedicated to stress testing our network and since the recent rebase of our fork with the libp2p master branch, this server gets OOM killed a lot.

In order to find out what was happening, our team has discovered that the configurability of the Kademlia bucket size (https://github.com/libp2p/rust-libp2p/pull/5414) has introduced a huge increase in memory allocation, which imply an increase in memory fragmentation. 

More precisely, it seems to be related to this code change : https://github.com/libp2p/rust-libp2p/commit/417968e07cfb79163a541ee2e5871a9bb6fe9534#diff-25d9554b592e6280d215bfc8b0bdb5a61eea3a6ca795849e6c7400414cb00c1cR288.

Previously, there was no heap allocation but now there is. 

### Expected behavior

Don't have heap allocation at every `get_closest_peers` request.

### Actual behavior

An allocation happens at every `get_closest_peers` request.

### Relevant log output

_No response_

### Possible Solution

Maybe use a `SmallVec` with the default `K_VALUE` in order to have the same behaviour than before ?

Or maybe use const generic ? It would not allow users to define the `K_VALUE` at runtime but it would allow them to define it in there code base.

### Version

_No response_

### Would you like to work on fixing this bug ?

Maybe

### PR DESCRIPTION
**Pull request by stormshield-frb**
## Description

Proposal to fix https://github.com/libp2p/rust-libp2p/issues/5712.

I have changed to `ClosestIter` structure to only allocate when `kbucket_size` is higher than `K_VALUE` and only once along the life of `ClosestIter`. I think I did not break anything but I would really like some experienced people with Kademlia to take a look (@guillaumemichel :wink:).

## Notes & open questions

~~I have kept the `sort_by` in the `Iterator` implementation of `ClosestIter` but I think we could remove every allocation whatsoever if we used `min_by` but I'm not sure that it would not change the research behaviour that's why I did not changed it. If experienced developers think that it would be equivalent I will do it.~~
It was a dumb question. I did not fully understood how the `ClosestIter` was working.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by elenaf9** [comment]
@guillaumemichel do you have some time to review this? I am unfortunately not so familiar with kademlia.

**Comment by guillaumemichel** [comment]
Yes, I will try to review before the end of week.

**Comment by vbhattaccmu** [comment]
Hi @guillaumemichel do we have any estimate when this branch will get merged? Currently we are running into memory growth on our p2p light clients as well and are using a [version](https://github.com/availproject/avail-light/blob/b06d05c0829e39724a18fafb77a608271367441e/Cargo.toml#L34) of libp2p after [this](https://github.com/libp2p/rust-libp2p/commit/417968e07cfb79163a541ee2e5871a9bb6fe9534#diff-25d9554b592e6280d215bfc8b0bdb5a61eea3a6ca795849e6c7400414cb00c1cR288) change was introduced. Having this change on latest commit will help us a lot. Thanks!

**Review by guillaumemichel — APPROVED** [review]
LGTM, thanks @stormshield-frb! Do you have benchmarks to share before and after the modifications?

**Comment by stormshield-frb** [comment]
@guillaumemichel thanks for your review.

Below, a picture of the allocations before this change (and after the bucket size configurability) using [`dhat`](https://valgrind.org/docs/manual/dh-manual.html). This was obtain by making between 100 and 500 (sorry cannot be any more precise) `get_closest_peers` call in 5 minutes.

image

After we don't have anything since there is no more allocation since everything is in the stack (we are using the default `K_VALUE`).

**Pull request merged**
