### PR TITLE
chore(perf): remove unused module

### PR DESCRIPTION
**Pull request by leonzchang**
## Description

Related: #3844.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by leonzchang** [comment]
Since this PR doesn't change any public API, I think bump the patch version will be ok?

**Comment by thomaseizinger** [comment]
Thanks for sending this!

I just had a look at the code and we seem to have a duplicate implementation here? Everything in `client/` and `server/` is actually unused. My IDE flags the modules as not included in the module tree.

Thus I think what you can do is simply delete these directories :)
Because the code is not included, we don't even need to bump version here.

**Comment by leonzchang** [comment]
> Thanks for sending this!
> 
> I just had a look at the code and we seem to have a duplicate implementation here? Everything in `client/` and `server/` is actually unused. My IDE flags the modules as not included in the module tree.
> 
> Thus I think what you can do is simply delete these directories :) Because the code is not included, we don't even need to bump version here.

Ok, fixed b77234f, will move on to the rest protocols

**Review by thomaseizinger — APPROVED** [review]
Always great to delete code! :)

Thanks!

**Comment by thomaseizinger** [comment]
cc @mxinden This seems to have been an oversight when you refactored it to use `libp2p-request-response`! I am not sure how close https://github.com/libp2p/rust-libp2p/pull/4382 is to be mergable but if that needs any of this code again, it can always just re-introduce it.

For now, deleting this allows us to make progress on #3844.

**Comment by thomaseizinger** [comment]
Hmm, this [new](https://github.com/libp2p/rust-libp2p/pull/4620) changelog lint that I introduced does have some funny side-effects in regards to non-changelog-worthy changes like this one.

**Comment by thomaseizinger** [comment]
> Hmm, this [new](https://github.com/libp2p/rust-libp2p/pull/4620) changelog lint that I introduced does have some funny side-effects in regards to non-changelog-worthy changes like this one.

Okay, I have a temporary fix in https://github.com/libp2p/rust-libp2p/pull/4658.

**Comment by mxinden** [comment]
Thank you for the clean-up @leonzchang!

@thomaseizinger agreed, don't need to wait for #4382.

**Pull request merged**
