### PR TITLE
chore: leverage `cargo`'s workspace inheritance

### LINKED ISSUE #3787: Unify and enforce same MSRV across workspace
## Motivation

Smaller caches.
Less complexity in CI and overall.

## Are you planning to do it yourself in a pull request?

Yes.

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

Previously, we would specify the version and path of our workspace dependencies in each of our crates. This is error prone as https://github.com/libp2p/rust-libp2p/pull/3658#discussion_r1153278072 for example shows. Problems like these happened in the past too.

There is no need for us to ever depend on a earlier version than the most current one in our crates. It thus makes sense that we manage this version in a single place.

Cargo supports a feature called "workspace inheritance" which allows us to share a dependency declaration across a workspace and inherit it with `{ workspace = true }`.

We do this for all our workspace dependencies and for the MSRV.

Resolves #3787.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
This is a breaking change now because it bumps MSRV.

**Comment by thomaseizinger** [comment]
@mxinden Should we enforce with a CI check that the version in the `workspace.dependencies` section is the same as in our `Cargo.toml`?

**Comment by thomaseizinger** [comment]
For the record, `cargo release version minor --execute` was a massive help in doing these version bumps. It even correctly bumped the version in the root manifest!

**Comment by thomaseizinger** [comment]
@mxinden I believe this is ready for merge now. Send it if you agree! We can then kick off merging the milestone!

**Review by mxinden — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Let's go!

**Pull request merged**
