### PR TITLE
Upgrade to Soketto 0.7.0

### PR DESCRIPTION
**Pull request by jsdw**

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Thanks @jsdw!

Do I understand correctly that `soketto` is not exposed on the API of `libp2p-websocket`? In other words, that this is not a breaking change?

Either way, would you mind including a changelog entry in `transports/websocket/CHANGELOG.md`?

Other than that, this looks good to me.

Do I understand correctly that this enables https://github.com/libp2p/rust-libp2p/pull/2085/?

**Comment by jsdw** [comment]
I'm not super familiar with this codebase yet, so I reckon @dvdplm would be better equipped to answer those questions 🙂

(though offhand it looks like soketto isn't exposed publically at all, and so this does not introduce any breaking changes)

I'll add an entry to the changelog when Im next at a computer :)

**Comment by jsdw** [comment]
Looking at the changelog, there is already an entry for "update dependencies" for the current unreleased version, which I think this change falls into, so I don't believe there's a need to update the changelog.

**Comment by mxinden** [comment]
> Looking at the changelog, there is already an entry for "update dependencies" for the current unreleased version, which I think this change falls into, so I don't believe there's a need to update the changelog.

:+1: right, sorry, I missed that.

---

I don't have permissions to merge latest _master_ branch to your branch. Could you do so @jsdw?

**Comment by jsdw** [comment]
> I don't have permissions to merge latest master branch to your branch. Could you do so @jsdw?

Done!

**Comment by mxinden** [comment]
Mhhh, GitHub actions didn't show until now. Merged via https://github.com/libp2p/rust-libp2p/pull/2271. Thanks @jsdw!

**Pull request closed without merging**
