### PR TITLE
[multistream-select] Re-enable 'parallel negotiation'.

### PR DESCRIPTION
**Pull request by romanb**
This PR re-enables the "parallel negotiation" strategy for the dialer in `multistream-select` based on an estimate of the number of alternative protocols the dialer supports. In this strategy the dialer sends an `ls` request straight away to avoid repeated protocol proposals and roundtrips. Closes https://github.com/libp2p/rust-libp2p/issues/1847.

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Change looks good to me.

As far as I can tell the last patch of the series (https://github.com/libp2p/rust-libp2p/pull/1811) is deployed with the recent Polkadot release [v0.8.27](https://github.com/paritytech/polkadot/releases/tag/v0.8.27).

I would expect it to be too early to break compatibility with versions < v0.8.27. What do you think? If so, I would suggest not yet merging this pull request until Polkadot v0.8.28 is released.

**Comment by romanb** [comment]
> If so, I would suggest not yet merging this pull request until Polkadot v0.8.28 is released.

Sounds good to me.

**Comment by mxinden** [comment]
With [Polkadot v0.8.28-1](https://github.com/paritytech/polkadot/releases/tag/v0.8.28-1) released, I think we can move forward here. Any objections @romanb @tomaka?

**Comment by romanb** [comment]
I will go ahead with merging this today if there are no objections.

**Comment by romanb** [comment]
Published in `multistream-select-0.10.2`.

**Pull request merged**
