### PR TITLE
draft: introduce wasm-tests for websocket

### PR DESCRIPTION
**Pull request by andreasbros**
Adds wasm-tests for websocket transport to allow manually running WASM tests.

## Description

It appears after replacing Websocket WASM implementation, websocket transport doesn't work anymore in WASM. 
This PR provides a manual way of running WASM webocket connectivity test to reproduce the failure and potential identify the issue.

## Notes & open questions
This PR is still work in progress and provided Dockerfile.wasm-builder should be changed to allow automated testing.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — COMMENTED** [review]
Thank you for this!

Which problems to you see with the websocket transport? The transport is being tested as part of the interop suite and it seems to be working with:

- nim-libp2p
- js-libp2p
- go-libp2p
- rust-libp2p

See https://github.com/libp2p/rust-libp2p/actions/runs/6883336308/job/18723684832#step:5:1064.

**Comment by andreasbros** [comment]
> Thank you for this!
> 
> Which problems to you see with the websocket transport? The transport is being tested as part of the interop suite and it seems to be working with:
> 
> * nim-libp2p
> * js-libp2p
> * go-libp2p
> * rust-libp2p
> 
> See https://github.com/libp2p/rust-libp2p/actions/runs/6883336308/job/18723684832#step:5:1064.

Thanks @thomaseizinger, I am not sure yet why interop-tests do not catch this issue. 
I have described the issue here: https://github.com/libp2p/rust-libp2p/issues/4872

**Comment by thomaseizinger** [comment]
@andreasbros I kicked CI which is currently blocked on you being a new contributor.

To make iteration smoother, perhaps find yourself a typo / small rewording or some other small thing that we can merge instantly as a separate PR so you can iterate in here without me having to approve each CI run!

**Comment by andreasbros** [comment]
> To make iteration smoother, perhaps find yourself a typo / small rewording or some other small thing that we can merge instantly as a separate PR so you can iterate in here without me having to approve each CI run!

@thomaseizinger I have created this small PR: https://github.com/libp2p/rust-libp2p/pull/4915. Thanks!

**Pull request closed without merging**
