### PR TITLE
Cargo.toml: Remove deprecated executor-specific features

### PR DESCRIPTION
**Pull request by thomaseizinger**
# Description

## Links to any relevant issues

- https://github.com/libp2p/rust-libp2p/pull/2962
- https://github.com/libp2p/rust-libp2p/pull/2173

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
Thank you @thomaseizinger!

**Comment by thomaseizinger** [comment]
This is blocked on the `0.49` release: https://github.com/libp2p/rust-libp2p/pull/2931

**Review by mxinden — APPROVED** [review]
@thomaseizinger thanks for preparing this. Can you bump the version in the root level `Cargo.toml`? Otherwise this looks good to me.

**Review by mxinden — APPROVED** [review]
Looks good to me. Thanks for the follow-up.

**Comment by thomaseizinger** [comment]
Interop tests fail for the same reasons as recently: We are bumping the version to 0.50 in this PR but testground doesn't yet know about that.

Proceeding with merge.

**Pull request merged**
