### PR TITLE
Issue 434

### PR DESCRIPTION
**Pull request by twittner**
Replaces the former odd/even distinction of IDs.

Addresses issue #434.

### CODE REVIEW

**Comment by twittner** [comment]
The PR has been re-based on top of the latest mplex changes and should be re-reviewed before merging.

**Comment by tomaka** [comment]
Re-reading this, are you sure that the behaviour is compatible with the Js and Go codes?
I would expect that the dialer is always the one node that negotiated the mplex protocol, while this code assumes that the dialer is always the local node.

**Comment by twittner** [comment]
> this code assumes that the dialer is always the local node.

It should not. It only picks `Dialer` in `open_outbound`. If you think of the line `let endpoint = elem.endpoint().unwrap_or(Endpoint::Dialer);` it defaults to `Dialer` for open frames (which are the only ones without explicit endpoint) because receiving open frames means we should store `(<u32>, Listener)` and the next line negates the endpoint (which is a bit opaque). Did I get you right or were you thinking of something else?

**Comment by tomaka** [comment]
That's what I'm saying: you always use `Dialer` when we open a substream, and `Listener` when we receive a substream. In other words, the local node is always considered as the `Dialer` and the remote always considered as the `Listener`.

I haven't checked the Js and Go code, but it would make sense to me that they fix the roles at the beginning.

**Comment by twittner** [comment]
The [proposed spec update](https://github.com/libp2p/mplex/blob/ec210bd2d0c783ae36c973017275429bf2a8e5e2/README.md#opening-a-new-stream) states:

> To open a new stream, first allocate a new stream ID. [...] The party that opens a stream is called the stream initiator. This is used to identify whether the message comes from a channel opened locally or remotely. Thus, the stream initiator always uses even flags and stream receivers uses odd flags.

My understanding is therefore that the roles are defined *per stream*.

**Comment by tomaka** [comment]
That's weird, but I guess we will go with it.
We should also open an issue to remove the even/odd substreams system in a few months or so.

**Pull request merged**
