### PR TITLE
Fix build with secp256k1 disabled

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
Change looks good to me, thanks for the patch. @vorot93 if you could include the diff below, I can cut a patch release of `libp2p-core` right away.

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 81c74f28..62705acc 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -41,6 +41,11 @@
 
 # `libp2p` facade crate
 
+## Version 0.37.2 [unreleased]
+
+- Update individual crates.
+    - `libp2p-core`
+
 ## Version 0.37.1 [2021-04-14]
 
 - Update individual crates.
@@ -61,7 +66,7 @@
     - `libp2p-swarm`
     - `libp2p-wasm-ext`
     - `libp2p-yamux`
-    
+
 - Drop support for `wasm32-unknown-unknown` in favor of
   `wasm32-unknown-emscripten` and `wasm32-wasi` [PR
   2038](https://github.com/libp2p/rust-libp2p/pull/2038).
diff --git a/Cargo.toml b/Cargo.toml
index 2928d5a0..671ac9fe 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -64,7 +64,7 @@ atomic = "0.5.0"
 bytes = "1"
 futures = "0.3.1"
 lazy_static = "1.2"
-libp2p-core = { version = "0.28.2", path = "core",  default-features = false }
+libp2p-core = { version = "0.28.3", path = "core",  default-features = false }
 libp2p-floodsub = { version = "0.29.0", path = "protocols/floodsub", optional = true }
 libp2p-gossipsub = { version = "0.30.0", path = "./protocols/gossipsub", optional = true }
 libp2p-identify = { version = "0.29.0", path = "protocols/identify", optional = true }
diff --git a/core/CHANGELOG.md b/core/CHANGELOG.md
index c469754b..d4f3a99f 100644
--- a/core/CHANGELOG.md
+++ b/core/CHANGELOG.md
@@ -1,3 +1,7 @@
+# 0.28.3 [2021-04-26]
+
+- Fix build with secp256k1 disabled [PR 2057](https://github.com/libp2p/rust-libp2p/pull/2057].
+
 # 0.28.2 [2021-04-13]
 
 - Update dependencies.
diff --git a/core/Cargo.toml b/core/Cargo.toml
index 6b910042..1836d90b 100644
--- a/core/Cargo.toml
+++ b/core/Cargo.toml
@@ -2,7 +2,7 @@
 name = "libp2p-core"
 edition = "2018"
 description = "Core traits and structs of libp2p"
-version = "0.28.2"
+version = "0.28.3"
 authors = ["Parity Technologies <admin@parity.io>"]
 license = "MIT"
 repository = "https://github.com/libp2p/rust-libp2p
```

**Comment by vorot93** [comment]
@mxinden done

**Review by mxinden — APPROVED** [review]
Thanks.

**Comment by mxinden** [comment]
[Tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-core-0.28.3) and [published](https://crates.io/crates/libp2p-core/0.28.3).

**Pull request merged**
