### PR TITLE
WIP: Join multicast group on all interfaces

### PR DESCRIPTION
**Pull request by eskimor**
Fix issue #1518.

We now join the multicast group on all interfaces, instead of just the default interface. This definitely fixes the node discovery for me. Initially I mentioned that there is also a problem with the `query_socket`, but I don't think this is true (it does not make sense and everything seems to work with this change). Nevertheless I will do some more testing on Monday and provide an additional PR for that problem if need be.

### CODE REVIEW

**Comment by eskimor** [comment]
Turns out younger me was right, query socket needs fixing as well.

**Comment by mxinden** [comment]
Depending on all of `pnet` just to get the hosts seems worrisome. See this discussion https://github.com/libp2p/rust-libp2p/pull/1514#issuecomment-603817280.

Are there any smaller crates out there offering the same functionality?

**Comment by eskimor** [comment]
Thanks @mxinden! I believe so, I am currently investigating [multicast-socket](https://github.com/bltavares/multicast-socket), which actually does exactly what we need and does not rely on pnet. Looks promising so far.

**Comment by romanb** [comment]
I believe this is already done now as part of https://github.com/libp2p/rust-libp2p/pull/1830. Feel free to open new issues if the approach taken there seems inadequate or incorrect to you.

**Comment by eskimor** [comment]
Looks good to me :-)

**Pull request closed without merging**
