### PR TITLE
src/tutorials/hole-punching: Clarify use of libp2p-lookup

### PR DESCRIPTION
**Pull request by winksaville**
Also, add some additional instructions for setting RELAY_SERVER_IP.

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Appreciated. Thanks @winksaville!

**Comment by winksaville** [comment]
The branch is out-of-date, should I change the "Update branch" to "Update with rebase" or leave it at "Update with merge commit"?

**Comment by mxinden** [comment]
> The branch is out-of-date, should I change the "Update branch" to "Update with rebase" or leave it at "Update with merge commit"?

No need to update the branch. I can do this through the UI as I just did. In general, I prefer merge commits over rebases, as that does not change history and thus does not requires a reviewer to start from scratch, but only requires a reviewer to review the additional changes.

**Comment by mxinden** [comment]
Not sure why CI is failing though:

```
error: unknown start of token: `
 --> src/tutorials/hole_punching.rs:100:1
  |
4 | ``` bash
  | ^
  |
help: Unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it is not
```

**Comment by winksaville** [comment]
That's weird, I'll take a look later today.

**Comment by winksaville** [comment]
Turns out the error was caused by the indentation being 4 rather than 3 spaces as I explained in the second commit! I've decided to change the other 3 sections too three spaces so there would be consistency.

I have kept the two commits so you can see the change, but maybe these two changes should be squashed,
which I can do if you want, or you can leave it as two or squash it when merging or ...

I've tested with `cargo test --workspace --no-default-features` and it failed before the change and now succeeds!

Anyway, let me know what more, if anything, you'd like me to do.

**Comment by mxinden** [comment]
Thanks for the help @winksaville!

**Pull request merged**
