### PR TITLE
chore: fix several typos in documentation

### PR DESCRIPTION
**Pull request by Frierened**
## Notes & open questions

Few typo comments fix in ./transports. Those changes don't require any testing or changelog entry I believe.

None

## Change checklist

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Thank you! :)

**Comment by drHuangMHT** [comment]
ping @thomaseizinger stalled PR here due to failing tests.

**Comment by drHuangMHT** [comment]
Still not be able to merge ping @thomaseizinger . The bot reported permission denied, did the token expired or something?

**Comment by thomaseizinger** [comment]
> Still not be able to merge ping @thomaseizinger . The bot reported permission denied, did the token expired or something?

Thank you. It is an unfortunate limitation of mergify that it can't merge PRs if it needs to update them with a diff that changes workflow files.

**Pull request merged**
