### PR TITLE
ci: enforce PR titles to follow the conventional commit specification

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

As per decision in https://github.com/libp2p/rust-libp2p/pull/3083, we want to use the conventional commits in our repository. To make sure this actually happens, this patch adds a workflow that validates PR titles to follow this convention. Together with our mergify configuration, these PR titles end up being the commit message title when squash-merging a pull request.

Related: https://github.com/libp2p/rust-libp2p/pull/3083
Related: https://github.com/libp2p/github-mgmt/pull/93

## Notes

I've copied the workflow from https://github.com/libp2p/github-mgmt/pull/93. Once this is merged, we will have to add this as a required check there as well. We could do that in an atomic manner by adding the workflow via the `mgmt` repository. Although that makes iteration slightly more annoying.

I'd suggest we add the workflow here first and once we are happy with the configuration and see it working, we enforce its presence (and it passing) via https://github.com/libp2p/github-mgmt.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
:pray:

**Review by jxs — APPROVED** [review]

**Comment by thomaseizinger** [comment]
What do we think about also limiting the length of the PR title to 72 such that we follow common Git guidelines?

**Comment by mxinden** [comment]
Works for me @thomaseizinger.

**Comment by thomaseizinger** [comment]
Here is the PR for it: https://github.com/libp2p/rust-libp2p/pull/3267

**Pull request merged**
