### PR TITLE
Readd lost noise upgrades.

### PR DESCRIPTION
**Pull request by romanb**
This readds the (non-standardised/specced) `UpgradeInfo` implementations for `IK` and `IX` to `X25519Spec` which got lost in the back-and-forth of https://github.com/libp2p/rust-libp2p/pull/1545. It also enables the `async-std` feature for the `libp2p-tcp` dependency in the tests, so that the `libp2p-noise` tests compile again on their own.

### CODE REVIEW

**Comment by romanb** [comment]
Any volunteers? Shouldn't be controversial.

**Comment by tomaka** [comment]
> Shouldn't be controversial.

Well it kind of is, since the comment saying that this isn't standard is easy to miss.
If this PR had been in when I upgraded Substrate to libp2p 0.19, we would probably accidentally be using a non-standard noise right now.

**Comment by romanb** [comment]
If there was something controversial about continuing to support other handshake patterns, that was the topic of https://github.com/libp2p/rust-libp2p/pull/1545 - this PR just corrects an oversight in that PR, where I understood that you're ok with it. I don't think we (or other libp2p implementations) have limited ourselves strictly to what is defined in the specs before, so I think it is unproblematic to support features beyond those specs. I'm ok with changing that direction, but then it would need to be enforced much more strictly that anything that isn't specced and requires support from all nodes participating in a protocol mustn't be implemented due to the possibility of incompatibility.

**Comment by tomaka** [comment]
I'm not familiar enough with the general state of the libp2p specs regarding noise to have an actual opinion on this, I'm just trusting you here.

**Pull request merged**
