### PR TITLE
ci: use nextest in CI

### PR DESCRIPTION
**Pull request by galargh**
WIP: checking out https://nexte.st/

#### Testing

Comparing test runtime **only** between https://github.com/libp2p/rust-libp2p/actions/runs/1847715973 and https://github.com/libp2p/rust-libp2p/actions/runs/1848112701

###### --no-default-features

`104.76s` (`nextest --no-default-features`) + `57.26s` (`test --doc --no-default-features`)
vs.
`183.36s` (`test --no-default-features`)

###### --all-features

`102.75s` (`nextest --all-features`) + `60.68` (`test --doc --all-features`) 
vs.
`196.72` (`test --all-features`)

### CODE REVIEW

**Comment by galargh** [comment]
@mxinden I saw a tweet about `nextest` yesterday (https://twitter.com/sunshowers6/status/1493283867297337345). As you can see in this draft, I created a very basic setup that uses it. It looks like there might be something to the speedup promises. The output of `nextest` looks pretty nice too. Anyway, I thought you might be interested in checking it out.

**Comment by mxinden** [comment]
Ah, cool. Thanks for testing this out.

I don't have a strong opinion here. I would appreciate faster CI runs. Though I am afraid I don't have much capacity to spend on the rust-libp2p CI setup, thus I would favor simplicity over execution time. In other words I would favor `cargo test` over `cargo nextest`.

**Comment by mxinden** [comment]
Ideally we would have a single CI configuration setup across all Rust based projects at Protocol Labs, similar to the unified CI setup on the Go side. Are you aware of such an effort @galargh? Is this tracked somewhere?

I am happy to help, though I don't have the capacity to drive this.

**Comment by galargh** [comment]
> Ideally we would have a single CI configuration setup across all Rust based projects at Protocol Labs, similar to the unified CI setup on the Go side. Are you aware of such an effort @galargh? Is this tracked somewhere?

It will be tracked here: https://github.com/protocol/.github/issues/251

So far, I've only been able to help set up CI in https://github.com/filecoin-project/ref-fvm/tree/master/.github which gave me a bit of an introduction to how Rust is built. 

I'm hoping I will be able to extrapolate from that experience and what I've seen here to create an initial version of unified setup. 

However, this work has not been scheduled yet. I will keep you in the loop once it gets more traction. 

> I don't have a strong opinion here. I would appreciate faster CI runs. Though I am afraid I don't have much capacity to spend on the rust-libp2p CI setup, thus I would favor simplicity over execution time. In other words I would favor cargo test over cargo nextest.

Let me close this for now then as it does require more evaluation. I'll revisit this once the unified CI for Rust initiative is more advanced.

Thank you for the response :)

**Pull request closed without merging**
