### PR TITLE
docs: update security policy with private vulnerability reports info

### PR DESCRIPTION
**Pull request by galargh**
## Description

This PR updates the security policy to encourage users to file security vulnerability reports through https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

The private vulnerability reports will show up here: https://github.com/libp2p/rust-libp2p/security/advisories?state=triage
The maintainers will receive GitHub notification about new private vulnerability reports. 

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — APPROVED** [review]

**Review by mxinden — COMMENTED** [review]
Looks good to me. Thanks @galargh. I am assuming that this has been tested with a GitHub account that doesn't have any special permissions on the libp2p organization. Is that correct?

Would you mind updating the root `README.md` here as well?

https://github.com/libp2p/rust-libp2p/blob/5b4eab7bafe6cba8fea6c806027ea680662b7cc6/README.md?plain=1#L16-L18

**Comment by galargh** [comment]
> Looks good to me. Thanks @galargh. I am assuming that this has been tested with a GitHub account that doesn't have any special permissions on the libp2p organization. Is that correct?

Yes! Not on this repo but I did test the flow where the user has no affiliation whatsoever with the target repository (using https://github.com/web3-bot and https://github.com/protocol/github-mgmt-template to be exact).

> Would you mind updating the root `README.md` here as well?

Done! https://github.com/libp2p/rust-libp2p/pull/3168/commits/a9862edb77b37509bdfbe4522f86a81d3822db17

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
And could you include the update to the template below as well?

https://github.com/libp2p/rust-libp2p/blob/5b4eab7bafe6cba8fea6c806027ea680662b7cc6/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L8

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Adding `send-it` label to mark that we want to merge this as soon as we have #3213 sorted.

**Pull request merged**
