### PR TITLE
feat(swarm): Show task `spawn` paths in tokio-console

### PR DESCRIPTION
**Pull request by oblique**
## Description

This PR adds `#[track_caller]` on all `spawn` wrappers.

## Notes & open questions

`#[track_caller]` on a trait does not affect or break its definition.

**Before**
screenshot_2024-06-11_15-45-16

**After**
screenshot_2024-06-11_16-00-54

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by dhuseby** [comment]
@oblique we have a rust-libp2p maintainer's call every two weeks that I think you should attend. The next one is starting right now: https://lu.ma/2024-07-02-rust-libp2p

The one after that is in two weeks: https://lu.ma/2024-07-16-rust-libp2p

**Review by jxs — COMMENTED** [review]
Hi Yianis, thanks for this. Can you explain the difference in the two pictures that putting `#[track_caller]` addresses? And shouldn't this be covered in `tokio` instead, like [this](https://github.com/tokio-rs/tokio/pull/4483) PR addresses? Thanks!

**Comment by oblique** [comment]
> Can you explain the difference in the two pictures that putting `#[track_caller]` addresses?

In the **before** picture, all libp2p's tasks show that they started from `executor.rs:41`, which actually is a wrapper function to `tokio::spawn`.

In the **after** picture you can see `pool.rs:538` and `pool.rs:437`, which are correct place that the tasks were spawned by the wrapper.

> And shouldn't this be covered in tokio instead, like https://github.com/tokio-rs/tokio/pull/4483 PR addresses?

Tokio covers this. However, because we define a wrapper to `tokio::spawn` we are responsible to propagate this tracking mechanism.

**Review by jxs — DISMISSED** [review]
Ok thanks LGTM!

**Review by jxs — APPROVED** [review]

**Pull request merged**
