### PR TITLE
Upgrade if-watch to fix windows crate vulnerability

### PR DESCRIPTION
**Pull request by TheQuantumPhysicist**
Hello

This is important and should be merged ASAP as it fixes a vulnerability

https://github.com/microsoft/windows-rs/commit/afe32525c22209aa8f632a0f4ad607863b51796a

Please create a new release after merging this.

Thank you.

### CODE REVIEW

**Comment by rkuhn** [comment]
Thanks for raising this! The wording is a bit too hasty, though, as there is no actual vulnerability being fixed — since no code changes were necessary in if-watch, all handlers were `Send` already. Still good to keep things updated :-)

**Comment by thomaseizinger** [comment]
Additionally, the new version is semver compatible so any end-user can already update to this version: `cargo update -p if-watch` should do the trick.

I guess we should still merge this because it is not good to allow a version that can cause a security problem.

**Review by mxinden — COMMENTED** [review]
Looks good to me, though needs a patch version bump on `libp2p-mdns` and `libp2p-tcp` and a changelog entry each. See https://github.com/libp2p/rust-libp2p/blob/master/docs/release.md#development-between-releases.

**Comment by mxinden** [comment]
> Additionally, the new version is semver compatible so any end-user can already update to this version: `cargo update -p if-watch` should do the trick.

Agreed here. Thus I won't cut a new release right away. @TheQuantumPhysicist let us know in case we are missing something.

**Comment by TheQuantumPhysicist** [comment]
You got it right guys. Though to clarify, the motivation for this is that every audit software, including git's dependabot, was screaming that there's a vulnerability, which we don't dismiss usually to avoid mistakes. I think with a precise update of if-watch (which wasn't possible before for the windows crate alone) the problem can be solved and this isn't super-urgent. Cheers!

**Comment by mxinden** [comment]
> Looks good to me, though needs a patch version bump on `libp2p-mdns` and `libp2p-tcp` and a changelog entry each. See https://github.com/libp2p/rust-libp2p/blob/master/docs/release.md#development-between-releases.

Closing here since these are still missing. Feel free to comment or open a new pull request in case you still want this updated.

**Pull request closed without merging**
