### PR TITLE
[On ice] Gossipsub: an extensible baseline pubsub protocol,  based on randomized topic meshes and gossip

### PR DESCRIPTION
**Pull request by jamesray1**
This partially implements the spec, with some variations around error handling and using message hashes and topic hashes. Control-message piggy-backing is not implemented, however you can `graft_peers_to_topics()`, `graft_peer_to_topics()`, `graft_peers_to_topic()`, `graft_peer_to_topic()`, and the same for prune. `i_have()`, `i_want()`, and `heartbeat()` are not implemented, as well as `GossipSubConfig`, floodsub compatibility, testing and examples. I suggest that it is reviewed in addition to #898, and could possibly be merged wtih that.

Gossipsub is a scalable, efficient, extensible baseline pubsub (publish-subscribe, messaging) protocol for p2p networks and decentralized applications on top of them.

See the spec [here](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub).

> This is the specification for an extensible baseline pubsub protocol, based on randomized topic meshes and gossip. It is a general purpose pubsub protocol with moderate amplification factors and good scaling properties. The protocol is designed to be extensible by more specialized routers, which may add protocol messages and gossip in order to provide behaviour optimized for specific application profiles.

Unlike floodsub, which broadcasts or publishes a message of a topic to all peers that are subscribed to a topic in the network, gossipsub publishes to a subset of peers, known as the target mesh degree, which is chosen as 6 here and in [go-gossipsub](https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go). Peers request messages of a topic with an `IWant` message and state what they have recently seen in their cache of messages with an `IHave` message. This gossipsub implementation in Rust, once complete, will be scalable for decentralized, p2p networks, unlike floodsub, and is thus suited for networks that aim to be mainstream, such as [Ethereum 2.0](https://github.com/ethereum/eth2.0-specs) (as developed in [Rust](https://www.rust-lang.org/) with [paritytech/shasper](https://github.com/paritytech/shasper) and [sigp/lighthouse](https://github.com/sigp/lighthouse)), [parity-ethereum](https://www.parity.io/ethereum/), [Polkadot](https://polkadot.network/), as well as any other p2p network that uses Rust. 

Closes #521. Updated for the latest API with handlers like `ProtocolsHandler` and `NodeHandler`, `NetworkBehaviour`, `Topology`, etc.

Because gossipsub extends on floodsub and needs to be backwards compatible with it, gossipsub reimplements and adapts much of floodsub. Therefore, please let me know if any changes are made to floodsub, and avoid making changes if feasible.

## Donations
Donations to jamesray.eth are appreciated via https://gitcoin.co/grants/42/gossipsub. [Thanks to Philippe Castonguay, Peter Kieltyka and Ric Burton from 0xHorizon Games for a 30 ETH one-off donation](https://twitter.com/peterk/status/1089689124989210626). Donations also help for previous contributions towards Eth 2 development; Eth docs such as the [wiki](https://github.com/ethereum/wiki/wiki), [Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf); reviewing research on https://ethresear.ch and papers such as Casper FFG and CBC; plus potential future contributions towards Ethereum development e.g. with [paritytech/shasper](https://github.com/paritytech/substrate/), which unlike [sigp/lighthouse](https://github.com/sigp/lighthouse) uses [substrate](https://github.com/paritytech/substrate/), providing various benefits e.g. modularity, flexibility, integration of Wasm, libp2p, GRANDPA consensus, blockchain interoperability, automatic upgradability and governance.

See these timesheets for details of previous contributions from June 2017 until now: https://tinyurl.com/DoDspsht and https://tinyurl.com/Ethtimesht. I think it seems reasonable to work on this full-time after I get ~$36000 USD or DAI / $50000 AUD per year, or $3000 DAI per month. That's not much, and is probably undervalued, particularly given ~1.25 years FTE has been mostly unfunded, but it's enough to work on gossipsub and Eth 2, which will of course be [very useful](https://github.com/ethereum/wiki/wiki/Decentralized-apps-(dapps)).  I will work on this in proportion to how much funding I have. >3000 DAI/m, FT. 1500 DAI/m, at least 18 hours per week, etc. By linear interpolation and dimensional analysis, H/w = X DAI/m / 3000 DAI/m * 35 h/w = X * 0.016667 hr/wk, if total funding per average month is less than 3000 DAI, otherwise at least 35 hours per week.

## Grant applications
* Protocol Labs. Applied around June. They initially said that we should fund this, then requested a plan/timeline. I said I am not a big fan of them (probably because at that time I was still studying rust-libp2p, tokio, futures, libp2p, gossipsub, etc.) and would keep working on it. I think this was probably a dealbreaker for them.
* Ethereum Foundation (typeform): applied Jan 14 2019, also Jan 2018 for eth 2.0 development / [Drops of Diamond](https://github.com/Drops-of-Diamond/diamond_drops), with which I have made several other [grant applications](https://github.com/Drops-of-Diamond/diamond_drops/issues/18) for.
* https://github.com/w3f/Web3-collaboration/pull/69: rejected since they are taking a different direction with messaging protocols, and referring me upon my querying to https://github.com/w3f/messaging.
* ECF: Jan 30 2019 (typeform)
* https://github.com/aragon/nest/issues/132
* Spoke with Sigma Prime about getting support for gossipsub development, however they also have limited funding and have a deadline to meet the Serenity testnet by the end of March, and feel that their implementation of gossipsub (#898) is sufficient for their needs.
* WeTrust

See also https://twitter.com/JamesCRay01/status/1082138888037003264.

### CODE REVIEW

**Comment by tomaka** [comment]
If gossipsub needs to be compatible with floodsub on the protocol layer, I don't think you need to duplicate everything. You should be able to add a dependency on `libp2p-floodsub` and use the `FloodsubHandler` from gossipsub.

**Comment by jamesray1** [comment]
Thanks for the suggestion, yeah I was thinking about this more.

**Comment by jamesray1** [comment]
I started duplicating `FloodsubHandler` and also relevant parts, but am thinking it may perhaps be better to nest a `FloodsubHandler` in a `GossipsubHandler`, although it remains to be seen how that will work.

```
// TODO: use the FloodsubHandler, figure out the best way to do so.
// Also probably don't need to re-implement the same functionality from
// Floodsub, just reuse from FloodsubHandler, and implement the
// additional functionality.
// Could either have a FloodsubHandler nested in a GossipsubHandler, or // reduplicate FloodsubHandler and other needed stuff. It seems like the
// former option might be best, but not sure.
```

**Comment by dvdplm** [comment]
Feel free to ping me when you want a review. :)

**Comment by jamesray1** [comment]
Sure, will do. I think I only need to duplicate `FloodsubHandler` and import the rest. But since `FloodsubHandler` is a struct I can't implement it as a trait for `GossipsubHandler`, so I think it needs to be nested within it.

**Comment by jamesray1** [comment]
Ah I think I'll use an `OrUpgrade`.

**Comment by tomaka** [comment]
Theoretically I think that you only need to implement a `Gossipsub` struct that implements `NetworkBehaviour` and uses `Floodsub`.

**Comment by daogangtang** [comment]
Hi, I am ready to do some works on this, what's your problem now when implementing? @jamesray1

**Comment by jamesray1** [comment]
@daogangtang, I've been preparing/working on gossipsub since June, but lately have been getting into development again. TBH it's probably simpler for me to just work on this solo. There are plenty of TODOs and issues in this repo, why not have a look at some of those and see if any of those wet your whistle?

**Comment by jamesray1** [comment]
I'm confused. 

At the protocol level (like `protocol.rs` in floodsub), you need a different `ProtocolName`, which would analogously like floodsub go in a `GossipsubConfig`. The generated `rpc_proto.rs` is different, since `rpc.proto` is different. So it seems like you need a `GossipsubCodec` with its own `impl Encoder` and `impl Decoder`, a different `GossipubRpc`, in `GossipsubMessage` there are also added `signature` and `key` fields, although those should also be in `FloodsubMessage`. It seems like you also need a `GossipsubSubscription` and `GossipsubSubscriptionAction` to differentiate state from `Floodsub`, although maybe there's a workaround for that. Then I think you need types for control messages, plus analogous wrappers to floodsub like `GossipsubGraftPrune` and `GossipSubGraftPruneAction`.

Then at the handler level for the protocol, types like `GossipsubConfig` and `GossipsubRpc` would go in a `GossipsubHandler` (comparing with `FloodsubHandler`), `GossipsubCodec` would go in a `SubstreamState`, while the `ProtocolsHandler` doesn't look like it would need much modification, apart from renaming `FloodsubRpc` and `FloodsubConfig` to `GossipsubRpc` and `GossipsubConfig`, respectively.

**Comment by jamesray1** [comment]
Nevertheless, I'd rather keep creating gossipsub using what is available now, rather than what until further improvements to the library.

**Comment by jamesray1** [comment]
> I think it is hard to inherit Floodsub to implement Gossipsub now, maybe we should abstract a low pubsub behaviour for common use.

Pubsub is a generalized spec, concrete implementations include floodsub and gossipsub, while the latter extends on the former impl. FMI see https://github.com/libp2p/specs/tree/master/pubsub.

**Comment by tomaka** [comment]
> Pubsub is a generalized spec, concrete implementations include floodsub and gossipsub, while the latter extends on the former impl. FMI see https://github.com/libp2p/specs/tree/master/pubsub.

For me the spec is only relevant for what happens on the wire, so that all the implementations are interoperable. We don't have to mimic the structure of the specs when it comes to the structure of the code.

**Comment by jamesray1** [comment]
While implementing an `Encoder` for `GossipsubCodec` and encoding the control field, I have tried to convert the fields of a `message::ControlMessage` instance to the fields of a `rpc_proto::ControlMessage` in the following way:
```rust
        for control in item.control.into_iter() {
            let mut ctrl = rpc_proto::ControlMessage::new();
            ctrl.set_ihave(control.ihave.into_iter().collect());
            ctrl.set_iwant(control.iwant.into_iter().collect());
            ctrl.set_graft(control.graft.into_iter().collect());
            ctrl.set_prune(control.prune.into_iter().collect());
            proto.mut_control().push(control);
        }
```

However, I am getting a compiler error for each call to `collect()`, e.g.:
```
a collection of type protobuf::RepeatedField&lt;rpc_proto::ControlIHave&gt; cannot be built from std::iter::Iterator&lt;Item=message::ControlIHave&gt;

help: the trait std::iter::FromIterator&lt;message::ControlIHave&gt; is not implemented for protobuf::RepeatedField&lt;rpc_proto::ControlIHave&gt;rustc(E0277)

protocol.rs(110, 54): a collection of type protobuf::RepeatedField&lt;rpc_proto::ControlIHave&gt; cannot be built from std::iter::Iterator&lt;Item=message::ControlIHave&gt;
```

The problem is that the rpc_proto is generated automatically. I will need to think of a solution for this, but if anyone has any ideas, I'm all ears!

**Comment by jamesray1** [comment]
After a little thought I think I'll try to implement `Into<rpc::ControlIHave> for message::ControlIHave` etc.

**Comment by daogangtang** [comment]
> Have a happy new year!

Happy new year 2!

**Comment by daogangtang** [comment]
hi, I have another implementation in progress: https://github.com/daogangtang/rust-libp2p/tree/daogang-gossipsub/protocols/gossipsub
Hope to helpful. @jamesray1

**Comment by jamesray1** [comment]
@daogangtang I would prefer it if you could work on https://github.com/stepancheg/rust-protobuf/issues/338, to avoid doubling up.

**Comment by jamesray1** [comment]
If you want to work on gossipsub it's best if we not double up on work but instead collaborate to work on different parts. For instance in addition to https://github.com/stepancheg/rust-protobuf/issues/338 you could write tests for what I have done so far, or work on one of the TODOs. But let me know so then I can work on something different and we can complete it faster.

**Comment by daogangtang** [comment]
> If you want to work on gossipsub it's best if we not double up on work but instead collaborate to work on different parts. For instance in addition to [stepancheg/rust-protobuf#338](https://github.com/stepancheg/rust-protobuf/issues/338) you could write tests for what I have done so far, or work on one of the TODOs. But let me know so then I can work on something different and we can complete it faster.

Ok, I was reading https://github.com/stepancheg/rust-protobuf/issues/338 so reply lately. I think I can do some tests or other work on https://github.com/stepancheg/rust-protobuf/issues/338  .

**Comment by jamesray1** [comment]
@daogangtang you may want to go an work on something else there is no promise or agreement of funding now or when this project is completed. There may be a vague possibility of a grant once it is used for Ethereum 2.0 development.

**Comment by jamesray1** [comment]
Not sure why derive Hash for TopicMap/HashMap isn't working, seems like I need to manually impl Hash myself.

**Comment by jamesray1** [comment]
I am only getting errors outside of the gossipsub crate now, but not when I checkout to master and reset to be like upstream. When I `git pull upstream master` it is not getting all changes. The edition field in the root Cargo.toml is missing. Not sure what else. I could edit that manually but there might be other stuff missing. It seems that it isn't just an issue with rls-vscode as in a plain terminal cargo build also has the same errors, as well as the CI tests here, and `git pull upstream master` also in a plain terminal says there is nothing to update, which I can't understand why due to the above difference.

**Comment by jamesray1** [comment]
I'm having some difficulty writing `join_many()`, if anybody wants to give tips on what might be the best way to resolve the compiler errors surrounding ownership and passing environment variables into closures, that would be appreciated. One option is to store the closure in a struct with its result.

**Comment by jamesray1** [comment]
I can't afford to keep self-funding development.

**Pull request closed without merging**
