### PR TITLE
feat(kad): derive Copy for kbucket::key::Key

### PR DESCRIPTION
**Pull request by drHuangMHT**
## Description

Derive `Copy` for `kbucket::key::Key` and `kbucket::key::KeyBytes` because `Key` is almost always used with `PeerId`, which is `Copy`.
This will make it easier to iterate over kbuckets.

## Notes & open questions
Quality of life feature.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — APPROVED** [review]
LGTM, thanks! @drHuangMHT :rocket: this is ready to be merged right?

**Comment by drHuangMHT** [comment]
> LGTM, thanks! @drHuangMHT 🚀 this is ready to be merged right?

Not yet, still need to address clippy lints.

**Comment by drHuangMHT** [comment]
@jxs Staged, need a re-approval.

**Review by guillaumemichel — APPROVED** [review]
👍🏻

**Pull request merged**
