### PR TITLE
protocols/gossipsub: Fix metric name

### PR DESCRIPTION
**Pull request by pawanjay176**
Fix metric naming

### CODE REVIEW

**Review by divagant-martian — APPROVED** [review]
ty @pawanjay176

**Review by mxinden — APPROVED** [review]
Thanks for the catch.

Crossreferencing https://github.com/prometheus/client_rust/issues/52 here which would have caught this in debug mode.

**Comment by mxinden** [comment]
Mind adding an entry to https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/CHANGELOG.md @pawanjay176 ?

**Comment by pawanjay176** [comment]
@mxinden Done!

**Pull request merged**
