### PR TITLE
*: Prepare v0.46.0

### PR DESCRIPTION
**Pull request by mxinden**
Proposing to release v0.46.0, among other things to prevent folks from running into https://github.com/libp2p/rust-libp2p/issues/2715 (https://github.com/libp2p/rust-libp2p/pull/2720).

Anything else you would like to see included?

In regards to the stream multiplexing and listener work, I am happy to cut another release once all of that work merged. I don't think we have to block this release.

Blocked on:

- [ ] https://github.com/libp2p/rust-libp2p/pull/2733

### CODE REVIEW

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
The `core` changelog is missing here as far as I can tell.

I am okay with cutting another release. The breaking changes to the muxer are mostly internal to `libp2p` so shouldn't be a big thing.

**Comment by mxinden** [comment]
> The `core` changelog is missing here as far as I can tell.

Good catch. Thanks. Fixed.
 
> I am okay with cutting another release. The breaking changes to the muxer are mostly internal to `libp2p` so shouldn't be a big thing.

:+1:

**Comment by mxinden** [comment]
@thomaseizinger with the latest fix, can I interpret your comment above as an approval?

**Review by thomaseizinger — APPROVED** [review]

**Review by elenaf9 — APPROVED** [review]

**Comment by mxinden** [comment]
Running on https://kademlia-exporter.max-inden.de/ now. Planning to do the release in a bit.

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-autonat-0.5.0
- libp2p-core-0.34.0
- libp2p-dcutr-0.4.0
- libp2p-deflate-0.34.0
- libp2p-dns-0.34.0
- libp2p-floodsub-0.37.0
- libp2p-gossipsub-0.39.0
- libp2p-identify-0.37.0
- libp2p-kad-0.38.0
- libp2p-mdns-0.38.0
- libp2p-metrics-0.7.0
- libp2p-mplex-0.34.0
- libp2p-noise-0.37.0
- libp2p-ping-0.37.0
- libp2p-plaintext-0.34.0
- libp2p-relay-0.10.0
- libp2p-rendezvous-0.7.0
- libp2p-request-response-0.19.0
- libp2p-swarm-0.37.0
- libp2p-tcp-0.34.0
- libp2p-uds-0.33.0
- libp2p-wasm-ext-0.34.0
- libp2p-websocket-0.36.0
- libp2p-yamux-0.38.0
- v0.46.0

**Comment by mxinden** [comment]
Shout out to @elenaf9 and @thomaseizinger for the huge refactoring work that shipped in this release.

**Pull request merged**
