### PR TITLE
Add prefix to `KeypairIdentity` signature data in noise protocol

### PR DESCRIPTION
**Pull request by pawanjay176**
For the signature in the noise handshake payload, the [spec](https://github.com/libp2p/specs/tree/master/noise#the-libp2p-handshake-payload) states that

> The data to be signed is the UTF-8 string `noise-libp2p-static-key:`, followed by the Noise static public key, encoded according to the rules defined in section 5 of RFC 7748.

This PR prefixes the data for signing and verification with the prefix string to conform with the spec.

### CODE REVIEW

**Comment by tomaka** [comment]
Since libp2p-noise is used in production, this is a big breaking change that we can't just merge as is.
There needs to be some way to keep the old behaviour.

As a more general note, I think it's a better idea to not incrementally change libp2p-noise, but instead to make it fully conforming to the specs at once. I don't exactly know what "conforming to the specs" involves, however, as I don't know it in details.

**Comment by pawanjay176** [comment]
> As a more general note, I think it's a better idea to not incrementally change libp2p-noise, but instead to make it fully conforming to the specs at once

Thanks for the feedback :) I agree. This was the only issue I found in rust-libp2p while doing interop testing with nim-libp2p noise. Apart from this, rust seems to be fully compliant with the spec but I'll do some more testing against nim-libp2p and go-libp2p to make sure. 

> There needs to be some way to keep the old behaviour.

We could could add an additional condition in the `verify` function to verify the old signature format without the prefix so it would work with code already running in production. Is that what you meant by keeping old behaviour?

**Comment by AgeManning** [comment]
One (not very elegant) suggestion would be to maintain a duplicate `noise-spec` protocol (or alternatively we can keep spec changes in our fork). 

As @tomaka suggests, we could keep this updated with the spec (as the spec seems to be changing) as a separate protocol (although their protocol-id's collide) and users can use either protocol. 

Not entirely fan of this idea, but could be one way of handling future differences.

**Comment by tomaka** [comment]
> rust seems to be fully compliant with the spec

Oh that's great!

> Is that what you meant by keeping old behaviour?

I was thinking of having both `LegacyNoiseConfig` and `NoiseConfig` (or similar names). API breaking changes are fine as long as there's a way to use the current wire protocol.

> as the spec seems to be changing

Err, that's less great!

**Comment by pawanjay176** [comment]
> I was thinking of having both `LegacyNoiseConfig` and `NoiseConfig` (or similar names).

This looks like the best option in order to keep the old behaviour. So if we want to network with the old code, we would use `LegacyNoiseConfig` else the spec'd `NoiseConfig.

Is that right @tomaka ?

**Comment by tomaka** [comment]
Yes

**Comment by romanb** [comment]
Superseded by https://github.com/libp2p/rust-libp2p/pull/1545.

**Pull request closed without merging**
