### PR TITLE
fix(autonat): Skip unparsable multiaddr

### PR DESCRIPTION
**Pull request by jxs**
## Description
With this commit `libp2p-autonat` no longer discards the whole remote payload in case an addr is unparsable, but instead logs the failure and skips the unparsable multiaddr.

See libp2p#3244 for details.

## Notes
This now targets `master`

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by mxinden** [comment]
The below seems to be the error:

```
  rust-libp2p-headxrust-libp2p-headwebrtc-dialer-1    | [2023-01-20T13:45:44Z WARN  webrtc::peer_connection::peer_connection_internal] failed to open data channel: there already exists a stream with identifier
```

**Review by mxinden — APPROVED** [review]
Error seems unrelated to this patch. I will merge and thus retrigger CI.

**Comment by jxs** [comment]
> The below seems to be the error:
> 
> ```
>   rust-libp2p-headxrust-libp2p-headwebrtc-dialer-1    | [2023-01-20T13:45:44Z WARN  webrtc::peer_connection::peer_connection_internal] failed to open data channel: there already exists a stream with identifier
> ```

it's also reproduced [here](https://github.com/libp2p/test-plans/actions/runs/3990270518/jobs/6843709448#step:11:9403), might you have a hunch on what this might be @melekes ?
Thanks!

**Comment by jxs** [comment]
opened https://github.com/webrtc-rs/webrtc/pull/405

**Pull request merged**
