### PR TITLE
*: Fix various clippy warnings

### PR DESCRIPTION
**Pull request by umgefahren**
# Description

I just implemented some changes suggested by clippy.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Thank you!

We do run clippy in CI but with a reduced set of lints. Can we perhaps narrow that set down, now that we have fixed a couple more?

**Comment by umgefahren** [comment]
Yes we could do that. I'm wondering why clippy doesn't pick that up now. I think it might be because the actions still use actions-rs which is not really necessary anymore, since Rust comes with the runners now and actions-rs might be outdated. 

I could make an additional PR updating the Workflows.

Many projects also include some lints from the [restriction group](https://rust-lang.github.io/rust-clippy/master/). This could be considered.

**Comment by thomaseizinger** [comment]
> Yes we could do that. I'm wondering why clippy doesn't pick that up now. I think it might be because the actions still use actions-rs which is not really necessary anymore, since Rust comes with the runners now and actions-rs might be outdated.
> 
> I could make an additional PR updating the Workflows.

Feel free, I am always in favor of using tooling better.

> Many projects also include some lints from the [restriction group](https://rust-lang.github.io/rust-clippy/master/). This could be considered.

Feel free to open an issue with a list of suggestions so we can discuss it :)

**Review by mxinden — APPROVED** [review]
Thanks @umgefahren.

I will merge here, assuming that the above follow-ups happen in separate pull requests.

**Comment by mxinden** [comment]
Ignoring Testground failures for now. See https://github.com/libp2p/test-plans/pull/41.

**Pull request merged**
