### PR TITLE
feat(identify): add connection_id in event

### LINKED ISSUE #4980: Add `ConnectionId` in `Identify` events
### Description

Add a field `connection_id` in `protocols/identify/src/behaviour.rs:Event` so we can map the received event to the corresponding connection.

### Motivation

In order to identify which connection has been used to receive `Identify::Event` and to react on it, we need to have access to the `ConnectionId` so that we can have access to the `ConnectionInfo` of the corresponding connection.

Moreover, for debugging and logging purposes it would be very helpful. 

Some events do sometimes have the `connection_id` field (`ping`, `dht`, `dctur`) but other do not (`identify`, `request_response`, ...). Maybe that is something that could be uniformized across behaviours. If so, we would be open to work and participate on this, but it might be a different issue.

### Current Implementation

We cannot access the `ConnectionId` identifying were the `Identify` event came from.

### Are you planning to do it yourself in a pull request ?

Yes

### PR DESCRIPTION
**Pull request by stormshield-frb**
## Description

Fixes: #4980.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I'll set this to draft because it is a breaking change!

**Comment by dariusc93** [comment]
@stormshield-frb could you update this PR?

**Comment by stormshield-frb** [comment]
I've updated the PR and fixed some of the checks but I cannot manage to find why the `semver` check is failing sorry :/

**Comment by dariusc93** [comment]
That shouldnt be a blocker to the pr since it is happening in others too

**Review by guillaumemichel — APPROVED** [review]
LGTM! @jxs this one can also make it to the next release 👍🏻

**Review by jxs — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
