### PR TITLE
fix(ci): properly escape PR title

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

Within double quoted strings, bash tries to evaluate everything within backticks as a command. The GitHub security guide recommends to use an intermediary environment variable instead: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable

See https://github.com/libp2p/rust-libp2p/actions/runs/3889880383/jobs/6638520274#step:3:11.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Draft until I have confirmed that this works.

**Comment by mxinden** [comment]
In case another example is needed: https://github.com/libp2p/rust-libp2p/actions/runs/3893266711/jobs/6645662828

**Comment by thomaseizinger** [comment]
@mxinden @jxs Friendly ping, this is ready for review (and has a series of PRs depending on it).

**Comment by thomaseizinger** [comment]
Proof that it is working: https://github.com/libp2p/rust-libp2p/actions/runs/3907325150/jobs/6676432195#step:3:10

**Review by jxs — APPROVED** [review]
LGTM

**Pull request merged**
