### PR TITLE
chore: add funding.json

### PR DESCRIPTION
**Pull request by AgeManning**
## Description

This adds a FUNDING.json file to the main repo. This is required for various projects, however the immediate case is for registering for an optimism retropgf grant.

### CODE REVIEW

**Comment by guillaumemichel** [comment]
There is a conflicting `funding.json` introduced in https://github.com/libp2p/rust-libp2p/pull/5553 by @dhuseby, and IIUC potential grants would go the the Libp2p Core Fund.

I suggest to override [`funding.json`](https://github.com/libp2p/rust-libp2p/blob/cefd22b8846ab005b311d5a3bc3d90c7e3a67872/funding.json). Is there a requirement on the filename (`funding.json` vs `FUNDING.json`)?

cc: @jxs @dariusc93 @dhuseby @p-shahi @yiannisbot @MarcoPolo @aschmahmann

**Comment by AgeManning** [comment]
Oh Sorry. I didn't realise there was already another PR for this. 

My understanding is that other libp2p maintainer teams are applying for the retro grant funding independently. 

As we (Sigma Prime) have not received any funding for our new role as maintainers of rust-libp2p and we do plan to maintain this indefinitely, we had planned on applying for the retro funding which primarily covers the period since nucleation to help sustain this project long term. 

Any funding obtained, we do plan to distribute for past work and solely to rust-libp2p and related projects.

**Comment by guillaumemichel** [comment]
@AgeManning I don't have write permission on your branch. Could you please remove the older [`funding.json`](https://github.com/libp2p/rust-libp2p/blob/cefd22b8846ab005b311d5a3bc3d90c7e3a67872/funding.json)?

**Review by guillaumemichel — APPROVED** [review]

**Comment by dhuseby** [comment]
@AgeManning so what happened here? Did my funding.json get removed? I understand that independent maintainers are all applying separately. We need to figure out how to do this so that we can all do that.

**Comment by dhuseby** [comment]
Having merge wars over whose funding.json file gets into the repo is ridiculous.

**Comment by AgeManning** [comment]
@dhuseby - Apologies, didn't intend on having any merge wars. 

I thought we didn't have any `funding.json` when I made this PR (I was looking for the capital version which is used in other repos). 

I notice now you already made a PR to add this, with an OP projectId. Have you applied for an OP retro grant for rust-libp2p? 

Happy to line up a discussion about this if that is the case

**Comment by dhuseby** [comment]
@AgeManning I think this has all been sorted.

**Pull request merged**
