### PR TITLE
Update noise proto to match go-libp2p

### PR DESCRIPTION
**Pull request by ckousik**
# Description
This updates the noise protobuf to match the js and go-libp2p repositories. It replaces the data field with NoiseExtensions.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by rkuhn** [comment]
It seems from a casual inspection that this breaks network compatibility with any current user of the `data` field. In general, protobuf evolution proceeds only by adding optional or repeated fields.

**Comment by thomaseizinger** [comment]
Thanks!

We haven't even shipped QUIC yet so WebTransport is still a bit away. I am not sure this is necessary at the moment, also given the churn that is currently going on with proto 2 & 3.

**Comment by ckousik** [comment]
@thomaseizinger This is needed for the webrtc interop between go-libp2p. Still need to flesh it out so I've left it as a draft.

**Comment by thomaseizinger** [comment]
> @thomaseizinger This is needed for the webrtc interop between go-libp2p. Still need to flesh it out so I've left it as a draft.

Only once we implement `WebTransport` right? It shouldn't be required for regular noise handshakes.

**Comment by ckousik** [comment]
We had a similar issue where the noise handshake payload had been upgraded in Go and was still on a previous version in js. We use the noise handshake in webrtc, so the authentication handshake was failing. It got fixed after the payload proto in the js repository was upgraded. You may be right however, since I cannot get the current rust implementation to work with a js client even with the updated payload.

**Comment by thomaseizinger** [comment]
> We had a similar issue where the noise handshake payload had been upgraded in Go and was still on a previous version in js. We use the noise handshake in webrtc, so the authentication handshake was failing. It got fixed after the payload proto in the js repository was upgraded. You may be right however, since I cannot get the current rust implementation to work with a js client even with the updated payload.

Is this WebRTC? The roles are reversed there as per the spec but it is a bit hard to spot. Perhaps that is your issue :)

**Pull request closed without merging**
