### PR TITLE
chore: prepare libp2p v0.52.4

### PR DESCRIPTION
**Pull request by jxs**
## Notes & open questions

Bug fixes to be included:

- https://github.com/libp2p/rust-libp2p/pull/4644
- https://github.com/libp2p/rust-libp2p/pull/4672

Best effort:

- https://github.com/libp2p/rust-libp2p/pull/4029
- https://github.com/libp2p/rust-libp2p/pull/4349

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
Given that we are now using workspace dependencies and given that we bumped `libp2p-swarm` but haven't yet released it, I think we need to do both in one go. In other words, we can not release `libp2p-upnp` `v0.1.1`, given that it would depend on an unreleased version of `libp2p-swarm`, namely `v0.43.6`. Or am I missing something?

https://github.com/libp2p/rust-libp2p/blob/master/swarm/CHANGELOG.md

**Comment by jxs** [comment]
No no Max, thanks for clarifying I wasn't aware, can we then also release `libp2p-quic`?
And I'll also prepare its release

**Comment by mxinden** [comment]
Yes. Happy to do a large round of patch releases. Especially with https://github.com/libp2p/rust-libp2p/pull/4120.

**Comment by jxs** [comment]
Ok thanks Max, updated :)

**Comment by mxinden** [comment]
@thomaseizinger any objections to me cutting a full round of non-breaking releases?

**Comment by thomaseizinger** [comment]
> @thomaseizinger any objections to me cutting a full round of non-breaking releases?

Not at all :)

**Comment by thomaseizinger** [comment]
> @thomaseizinger any objections to me cutting a full round of non-breaking releases?

Before you do, can you please merge https://github.com/libp2p/rust-libp2p/pull/4349 and include it there?

**Comment by mxinden** [comment]
@jxs I updated title and description. The latter now links to the outstanding pull requests. 

Everyone, please post here in case I am missing any other pull request.

**Comment by thomaseizinger** [comment]
I just merged https://github.com/libp2p/rust-libp2p/pull/4680 because it gives us a deprecation that we can then remove later and `libp2p-swarm` is to be released anyway.

**Review by mxinden — APPROVED** [review]

**Comment by mxinden** [comment]
Still releasing. Very slow. Assuming due to https://github.com/crate-ci/cargo-release/issues/692.

**Comment by mxinden** [comment]
Published and tagged the following crates:

- libp2p-deflate-v0.40.1
- libp2p-dns-v0.40.1
- libp2p-gossipsub-v0.45.2
- libp2p-identify-v0.43.1
- libp2p-identity-v0.2.7
- libp2p-kad-v0.44.6
- libp2p-noise-v0.43.2
- libp2p-plaintext-v0.40.1
- libp2p-pnet-v0.23.1
- libp2p-quic-v0.9.3
- libp2p-relay-v0.16.2
- libp2p-rendezvous-v0.13.1
- libp2p-request-response-v0.25.2
- libp2p-swarm-v0.43.6
- libp2p-tcp-v0.40.1
- libp2p-upnp-v0.1.1
- libp2p-v0.52.4
- libp2p-webrtc-websys-v0.2.0-alpha
- libp2p-websocket-websys-v0.2.0

**Pull request merged**
