### PR TITLE
Fix decode data UnexpectedEof bug

### PR DESCRIPTION
**Pull request by TheWaWaR**
I think source data is empty not necessary return `UnexpectedEof`

### CODE REVIEW

**Comment by tomaka** [comment]
The error this PR removes happens if we need more data from the stream in order to finish the varint, but there is none.
For example if the data is just `0x81 0x81` then this will happen.

If you're seeing this error at a higher level, then it's probably the higher level that is at fault (for example, if it tries to decode a varint but something else is on the stream).

**Comment by TheWaWaR** [comment]
From my millions of lines of logs, about every 10 seconds to few minutes [here](https://github.com/tomaka/libp2p-rs/blob/725f9f78ebeddc038941316f120a99daaebc9231/mplex/src/codec.rs#L103) will encounter an `UnexpectedEof` error from `varint_decoder.decode`, this will:
*  cause `mplex::codec::next_match` fail
* then cause `core::connection_reuse::poll_incoming` fail
* then the corresponding connection dropped

After I remove the `UnexpectedEof` code, connection will never dropped like this, and all high level logic works just fine.

* * * * *

**PS**: There is another different `UnexpectedEof` will cause connection dropped (seems not related to current issue), the propagate path is:
* I haven't figure out where is the really source error yet : (
* then will cause [here](https://github.com/paritytech/polkadot/blob/a118a85230630e4b9267aa9277448c0a02e8f17d/substrate/network-libp2p/src/custom_proto.rs#L164) have an `UnexpectedEof` error
* then [here](https://github.com/paritytech/polkadot/blob/a118a85230630e4b9267aa9277448c0a02e8f17d/substrate/network-libp2p/src/service.rs#L807)
* then the connection dropped

**Comment by TheWaWaR** [comment]
Consider this test case in `varint-rs/src/lib.rs`:
``` rust
#[test]
fn can_decode_basic_biguint() {
    assert_eq!(
        BigUint::from(300u16),
        decode(&[0b10101100, 0b00000010][..]).unwrap()
    );
}
```

If there is only one byte supplied, then it will be an `UnexpectedEof`.
``` rust
#[test]
fn can_decode_basic_biguint() {
    assert_eq!(
        BigUint::from(300u16),
        decode(&[0b10101100][..]).unwrap()
    );
}
```

In an `IO` (network/fs) context, we can't know how many bytes we can read from a stream, maybe just one byte.

**Comment by tomaka** [comment]
This code is in an implementation of the decode trait of the tokio library.
Whether you're correct or not depends on how tokio uses the trait impl, and it's unfortunately super blurry.

**Comment by TheWaWaR** [comment]
How about the `can_decode_basic_biguint` test case?

**Comment by tomaka** [comment]
Sorry for the late answer.
I had a brainfart indeed, I didn't realize we were modifying `src` during the iteration. I should have re-read the code.

What confuses me is that there's no way to indicate an "unexpected EOF", but apparently tokio doesn't have a way to check that.

**Comment by TheWaWaR** [comment]
I think `tokio` will return a [`tokio::io::ErrorKind::UnexpectedEof`](https://docs.rs/tokio/0.1.7/tokio/io/enum.ErrorKind.html#variant.UnexpectedEof) error for this situation. Not sure though.

**Pull request merged**
