### PR TITLE
docs(readme): add homestar as notable user

### PR DESCRIPTION
**Pull request by bgins**
## Description

Add [Homestar](https://github.com/ipvm-wg/homestar) to the list of notable users. Homestar is an implementation of the InterPlanetary Virtual Machine (IPVM) specification.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Thanks!

**Comment by thomaseizinger** [comment]
@bgins I don't seem to have permission to update this branch. Can you fix that? It will otherwise be tricky to merge this because our merge bot can't update to latest master.

**Comment by bgins** [comment]
> @bgins I don't seem to have permission to update this branch. Can you fix that? It will otherwise be tricky to merge this because our merge bot can't update to latest master.

Alas, it seems I won't be able to on this PR. It seems that GitHub does not give you the option on cross-organization pull requests: https://github.com/orgs/community/discussions/5634

I would be happy to open a new PR from personal account to make it possible. Same with #4646. What do you think?

**Comment by thomaseizinger** [comment]
> I would be happy to open a new PR from personal account to make it possible. Same with #4646. What do you think?

Yeah I think that will overall be the simplest solution, otherwise we have to babysit this a lot.

**Comment by bgins** [comment]
Closed in favor of #4682.

**Pull request closed without merging**
