### PR TITLE
chore(gossispsub): deprecate futures-ticker

### PR DESCRIPTION
**Pull request by jxs**
## Description

to address [RUSTSEC-2024-0384 ](https://rustsec.org/advisories/RUSTSEC-2024-0384.html). Use `futures-timer` and `Delay` instead

### CODE REVIEW

**Comment by jxs** [comment]
will also update `if-watch` and cut a new release to then update this `Cargo.lock`

**Review by dariusc93 — COMMENTED** [review]
LGTM. Might want to bump the version in `Cargo.toml` and update the CHANGELOG.md :)

**Comment by jxs** [comment]
`cargo deny` is still failing due to https://github.com/rust-netlink/netlink-sys/pull/24#issuecomment-2483767352

**Review by dariusc93 — COMMENTED** [review]
Can we add `futures-timer/wasm-bindgen` to the `wasm-bindgen` feature?

**Comment by jxs** [comment]
> futures-timer/wasm-bindgen

yup, thanks Darius, added!

**Review by dariusc93 — APPROVED** [review]

**Comment by ruseinov** [comment]
Thanks for making this happen! It would be great to see a release that contains this change sometime soon.

**Comment by jxs** [comment]
hi @ruseinov thanks for the interest! we plan to release a new version soon! We're waiting for https://github.com/libp2p/rust-libp2p/pull/5595 to be merged and another one adding IDONTWANT support

**Pull request merged**
