### PR TITLE
floodsub - Removes hashing for topic identifier

### PR DESCRIPTION
**Pull request by peat**
If I understood the conversation around #473, the decision was to push the "hash or not to hash" decision up to the application, in order to be compatible with the Go and JS implementations and let app developers decide how they want to broadcast topics.

### Changes

I stripped everything down to a thin wrapper around the `rpc_proto::TopicDescriptor` and used `String` for the topic identifiers instead of creating another struct or type alias.

### Testing

Existing tests pass, and `examples/chat` works as expected. Please let me know if there's anything else expected. 😁

### CODE REVIEW

**Comment by tomaka** [comment]
Sorry for not getting back to you! I'm a bit hesitant on the design of this.

Is it fine for you if we delay this for after we merge the `stable-futures` branch to `master` (which needs async/await stabilization)?
I'd like to release a new version of rust-libp2p before that happens, and this PR would probably not make it.

**Comment by peat** [comment]
Of course, no problem. 👍

**Comment by rklaehn** [comment]
@tomaka now that the `stable-futures` branch has been merged, can this be warmed up and merged as well? It is something I need to talk to go-ipfs.

**Comment by rklaehn** [comment]
@peat I got this rebased to latest master at https://github.com/Actyx/rust-libp2p/tree/473-pubsub-topicid . Wanna take this and drag it over the finish line, or should I open a new PR with this?

**Comment by tomaka** [comment]
Done in #1395

**Pull request closed without merging**
