### PR TITLE
.circleci: Add script to test that Rust attributes are below comments

### PR DESCRIPTION
**Pull request by mxinden**
To safe me a couple of minutes next time I wonder whether attributes go above or below comments.

### CODE REVIEW

**Comment by tomaka** [comment]
We're kind of switching to GitHub Actions and out of CircleCI, so this would need to be done through GH actions.

(also, this would also be enforced by rustfmt, which I'm still in favour of)

**Comment by mxinden** [comment]
@tomaka could you take another look?

**Comment by tomaka** [comment]
I find it a bit exaggerated to have a test just for this, and I'd be in favour of just using rustfmt, but I'm also not really opposed to it.

You have to rename the script though, as we removed the `.circleci` directory.

**Comment by mxinden** [comment]
> I find it a bit exaggerated to have a test just for this.

Yes, agreed. In addition the more time I spend on this, the more I feel like falling victim to the sunk cost fallacy.

> and I'd be in favour of just using rustfmt

I second this. Even though this particular case would not be covered (as far as I can tell from a quick test).

**Pull request closed without merging**
