### PR TITLE
Addition of protocol relevant information

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Signed-off-by: Abhijith Ganesh <67182544+AbhijithGanesh@users.noreply.github.com>

# Description

Implementation of logs that will log the type of protocol used and other relevant information relevant to track usage.

## Links to any relevant issues

[Link to Issue](https://github.com/libp2p/rust-libp2p/issues/2758#issuecomment-1209712749)

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
@thomaseizinger and @mxinden I would need help with this, can you review the PR and tell me what I am missing?

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Thanks!

This is a good start. Can you please:

- Add some tests
- Integrate with the `Recorder` infrastructure of the `libp2p_metrics` crate to automatically increment and decrement a gauge based on a `SwarmEvent`

**Comment by AbhijithGanesh** [comment]
I shall do the required

**Comment by thomaseizinger** [comment]
Closing this in favor of https://github.com/libp2p/rust-libp2p/pull/2982.

**Comment by thomaseizinger** [comment]
Thanks for your work anyway @AbhijithGanesh ! I closed this here because #2982 is closer to being merged and I want to avoid duplicate work :)

**Pull request closed without merging**
