### PR TITLE
Add libp2p-quic.

### PR DESCRIPTION
**Pull request by dvc94ch**
Would be nice to support tls too, the tls parts from #1334 could be extracted and supported in this crate. This is however left for future work.

cc @Demi-Marie

### CODE REVIEW

**Comment by DemiMarie** [comment]
Please CC this account instead; the @Demi-Marie account is no longer used.

**Comment by mxinden** [comment]
Thanks for opening this up and thanks for offering your work to the rust-libp2p project.

As mentioned before I am not opposed to adding QUIC+Noise to rust-libp2p, though, before including it in rust-libp2p, there would need to be a corresponding specification in at least [_Recommended Draft_](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md#level-1-working-draft) stage, especially since I don't have enough experience to judge whether the construction is safe from a cryptographic standpoint.

We do have many unbounded buffers (e.g. various `Vec`s, `VecDequeue`s and `HashMap`s), which ideally I would like to get rid of in most cases to improve overall throughput, though most of these are within a single module, potentially removable without a breaking change. That said, I am very much opposed to an implementation using unbounded channels, especially as these oftentimes stretch across multiple modules.

Last but not least, unless we change our strategy of supporting both tokio and async-std, this crate would need to support both as well.

**Comment by dvc94ch** [comment]
> As mentioned before I am not opposed to adding QUIC+Noise to rust-libp2p, though, before including it in rust-libp2p, there would need to be a corresponding specification in at least Recommended Draft stage, especially since I don't have enough experience to judge whether the construction is safe from a cryptographic standpoint.

Is that stage 1 or stage 2 with one reference implementation? stage 3 requires at least two implementations which I don't have the time or interest to build a go/js version.

> We do have many unbounded buffers (e.g. various Vecs, VecDequeues and HashMaps), which ideally I would like to get rid of in most cases to improve overall throughput, though most of these are within a single module, potentially removable without a breaking change. That said, I am very much opposed to an implementation using unbounded channels, especially as these oftentimes stretch across multiple modules.

I don't think this actually increases throughput in many cases. It is better for preventing denial of service attacks. I guess this can not be done as a follow-up?

> Last but not least, unless we change our strategy of supporting both tokio and async-std, this crate would need to support both as well.

Also this one, can't be done as a follow-up? It is quite a chunk of work to support an additional executor. The if-watch/udp-socket would need support and spawning a task would be annoying to say the least. Probably an executor would need to be passed as an argument when creating a new transport.

**Comment by dvc94ch** [comment]
Anyway, when it comes to PL merging a spec, that isn't really up to me. I opened a PR, but they tend to spend years on their own specs, never mind a third party one.

**Comment by dvc94ch** [comment]
Well, not that I'm surprised how this went. PL never fails expectation.

**Comment by dvc94ch** [comment]
> As mentioned before I am not opposed to adding QUIC+Noise to rust-libp2p, though, before including it in rust-libp2p, there would need to be a corresponding specification in at least Recommended Draft stage

So there is a PR open to support tls in libp2p-quic [0]. Currently waiting on a new version of barebones-x509. Is supporting tls in addition to noise enough? We can expose the noise implementation behind an unstable-noise or experimental-noise or something like that. 

The tls version can't support 0-rtt and doesn't support keys other than ed25519 for compatibility with the noise implementation. Although with enough generics/traits we could change that.

- [0] https://github.com/ipfs-rust/libp2p-quic/pull/5

**Pull request closed without merging**
