### PR TITLE
feat: update async-std to 1.6.2

### PR DESCRIPTION
**Pull request by dignifiedquire**
~~(still testing, will mark as ready when I am confident it is working)~~

Ref #1612

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Ready for review, all tests are now passing out of the box, thanks to due diligent work from @stjepang

**Comment by tomaka** [comment]
I'm trying this on Polkadot and it seems to work so far. :rocket:

**Comment by tomaka** [comment]
I'm still going to test more, but I think it's ok to merge this.
I think we should wait for a couple days to put it in a release though.

**Comment by twittner** [comment]
Then we should wait with the merge until we have published the new libp2p version which will require `async-std` 1.5.0. If we merge this now we would use 1.6.2 as a lower bound.

**Comment by tomaka** [comment]
It's been running for 4 hours now, and there isn't any anomaly in sight.

**Comment by tomaka** [comment]
Let's merge this?

**Pull request merged**
