### PR TITLE
fix(ci): avoid rate limits on GitHub API by supplying auth token

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

This follows the recommendation in the `Usage` section of the action: https://github.com/arduino/setup-protoc#usage
We won't need it once #3024 is landed but the failing CIs are annoying enough to warrant a temporary fix.

Example of a failing CI run: https://github.com/libp2p/rust-libp2p/actions/runs/3630150537/jobs/6123169342

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
:pray:

**Comment by mxinden** [comment]
Testground failure is due to a rename:

```
failed to load composition file: failed to process composition template: open ping/_compositions/go-rust-interop-latest.toml: no such file or directory
```

https://github.com/libp2p/test-plans/pull/70

See https://github.com/libp2p/rust-libp2p/pull/2647#issuecomment-1335189994 for `libp2p-relay` and `libp2p-dcutr` failures.

**Comment by mxinden** [comment]
Not sure how successful this was. https://github.com/libp2p/rust-libp2p/pull/3191 is now rate limited with an API key.

**Comment by thomaseizinger** [comment]
> Not sure how successful this was. https://github.com/libp2p/rust-libp2p/pull/3191 is now rate limited with an API key.

Wow, so we replaced one error with another haha

**Pull request merged**
