### PR TITLE
refactor(metrics/identify): update to new collector trait

### PR DESCRIPTION
**Pull request by mxinden**
## Description

Updates to `prometheus-client` `Collector` trait refactor introduced with https://github.com/prometheus/client_rust/pull/149.

## Notes & open questions

Ready for review, though blocked to merge until https://github.com/prometheus/client_rust/pull/149 is released.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
LGTM. Essentially, the proposed design is a programmatic API for creating metrics right? I think that is a good model.

**Comment by mxinden** [comment]
Upgrading to `prometheus-client` `v0.22.0` is a breaking change given that `prometheus-client` is exposed in `libp2p-metrics` and `libp2p-gossipsub`. I am adding this pull request to the `v0.53.0` milestone.

**Comment by mxinden** [comment]
Converting to draft here given that we will only merge with v0.53.0 milestone.

**Comment by thomaseizinger** [comment]
@mxinden Can you cut a new release so we can remove the patch entry?

**Pull request merged**
