### PR TITLE
Don't panic in libp2p-websocket

### LINKED ISSUE #2598: Panic in `libp2p-websocket` at 'SinkImpl::poll_ready called after error.'
```
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    0: log_panics::init::{{closure}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    1: std::panicking::rust_panic_with_hook
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:702:17
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    2: std::panicking::begin_panic::{{closure}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    4: std::panicking::begin_panic
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    5: <quicksink::SinkImpl<S,F,T,A,E> as futures_sink::Sink<A>>::poll_ready
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    6: <rw_stream_sink::RwStreamSink<S> as futures_io::if_std::AsyncWrite>::poll_write
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    7: <multistream_select::negotiated::Negotiated<TInner> as futures_io::if_std::AsyncWrite>::poll_write
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    8: <libp2p_noise::io::framed::NoiseFramed<T,S> as futures_sink::Sink<&alloc::vec::Vec<u8>>>::poll_ready
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    9: <libp2p_noise::io::framed::NoiseFramed<T,S> as futures_sink::Sink<&alloc::vec::Vec<u8>>>::poll_flush
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   10: <libp2p_noise::io::NoiseOutput<T> as futures_io::if_std::AsyncWrite>::poll_flush
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   11: multistream_select::negotiated::Negotiated<TInner>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   12: <multistream_select::negotiated::Negotiated<TInner> as futures_io::if_std::AsyncWrite>::poll_close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   14: <S as futures_core::stream::TryStream>::try_poll_next
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   15: <futures_util::stream::try_stream::ErrInto<St,E> as futures_core::stream::Stream>::poll_next
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   16: <libp2p_yamux::Yamux<S> as libp2p_core::muxing::StreamMuxer>::close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   17: <libp2p_core::muxing::Wrap<T> as libp2p_core::muxing::StreamMuxer>::close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   19: tokio::runtime::task::harness::poll_future
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   20: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   21: std::thread::local::LocalKey<T>::with
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   22: tokio::runtime::thread_pool::worker::Context::run_task
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   23: tokio::runtime::thread_pool::worker::Context::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   24: tokio::macros::scoped_tls::ScopedKey<T>::set
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   25: tokio::runtime::thread_pool::worker::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   26: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   27: tokio::runtime::blocking::pool::Inner::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   28: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   29: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:       std::sys::unix::thread::Thread::new::thread_start
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys/unix/thread.rs:108:17
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   31: start_thread
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   32: clone
```

I don't know how to reproduce the bug, but it seemed likely to be fixable without reproduction.

CC https://github.com/nimiq/core-rs-albatross/issues/732

### PR DESCRIPTION
**Pull request by hrxi**
Return an error instead. `quicksink` panics if you call a method after
it returned an error once.

Fixes #2598.

### CODE REVIEW

**Comment by mxinden** [comment]
Do I understand correctly that something within the stack is calling `SinkImpl::poll_ready` even though the previous call returned an error? If so, instead of silencing the error as suggested here, have you tried locating the logic that is responsible for this second try @hrxi?

**Comment by hrxi** [comment]
> Do I understand correctly that something within the stack is calling `SinkImpl::poll_ready` even though the previous call returned an error?

This is correct.

> If so, instead of silencing the error as suggested here, have you tried locating the logic that is responsible for this second try @hrxi?

The pull request does not silence an error, it will return with an error status once any error has been observed.

To me, this seems like a strict improvement over the panic semantics, in fact the authors of quicksink also approved a pull request with this behavior: https://github.com/paritytech/quicksink/pull/4. The pull request was reverted due to unrelated API concerns which don't apply to this change: https://github.com/paritytech/quicksink/pull/6/.

The original pull request also included a usage scenario, though I haven't evaluated its usefulness:

> This however makes it more difficult to use SinkImpl in certain contexts, e.g. concurrently using locks, when for instance one thread successfully closes the sink using poll_close and another one calls poll_ready afterwards (Thanks @romanb for this example).

**Comment by mxinden** [comment]
> have you tried locating the logic that is responsible for this second try

I would expect other `Sink` implementations to have similar behaviors, i.e. panic as well, thus I guess it is worth locating the component that retried after an error.

In which setup are you using the `Connection` @hrxi? Are you upgrading the `Connection` with a stream muxer?

**Comment by hrxi** [comment]
> I would expect other `Sink` implementations to have similar behaviors, i.e. panic as well, thus I guess it is worth locating the component that retried after an error.

I don't expect other `Sink` implementation to have similar behavior. Do you know of any? There was a quicksink issue about it and even the author of quicksink agreed that it's bad to panic there, but due to API concerns couldn't change it.

**Comment by jasl** [comment]
Just a friendly ping, any progress here? I heard other parachain teams also met this issue, don't know why `polkadot-v0.9.23` branch trigger very frequently

**Comment by bkchr** [comment]
@mxinden can we get this merged? Or should we open a pr with a better solution?

**Comment by tomaka** [comment]
As the conversation says, this PR is merely hiding the actual bug instead of fixing it, and it is IMO the wrong approach. If you want to help, you can help try to find the actual bug rather than pressuring to merge a PR.

**Comment by mxinden** [comment]
> Or should we open a pr with a better solution?

That would be very much appreciated.

Referencing @tomaka's suspicion: https://github.com/libp2p/rust-libp2p/issues/2598#issuecomment-1153622358

**Comment by bkchr** [comment]
Okay perfect. @kpp can you please look into @tomaka's suspicion?

**Comment by mxinden** [comment]
Fixed with `yamux` `v0.10.2`. See https://github.com/libp2p/rust-yamux/pull/138#issuecomment-1206103021

I am closing here. Thanks for the hep everyone!

**Pull request closed without merging**
