### PR TITLE
*: Prepare v0.34.0 release

### PR DESCRIPTION
**Pull request by mxinden**
I would like to release a new version of `libp2p` (`v0.34.0`) and new versions of its sub-crates.

I would suggest to wait for https://github.com/libp2p/rust-libp2p/pull/1917 to be merged before proceeding here. I don't think it is worth blocking the release for https://github.com/libp2p/rust-libp2p/pull/1916. https://github.com/libp2p/rust-libp2p/pull/1899 is blocked on a new release of `snow` (see https://github.com/libp2p/rust-libp2p/pull/1899#issuecomment-754096109).

@quininer @romanb do I understand correctly that we will hold off with https://github.com/libp2p/rust-libp2p/pull/1889 for now?

I do not plan to release a new version of `libp2p-secio` given its deprecation. Objections? I would even suggest removing the code in the future, only leaving a note with a reference to an older commit.

### CODE REVIEW

**Comment by romanb** [comment]
I would like to include #1889, if you have no objections.

> I do not plan to release a new version of libp2p-secio given its deprecation. Objections? I would even suggest removing the code in the future, only leaving a note with a reference to an older commit.

:+1:

**Comment by quininer** [comment]
I hope tokio 1.0 is included. I don't mind delaying #1889, because it has no API changes, so it can be released in a patch version.

**Comment by mxinden** [comment]
> I hope tokio 1.0 is included.

@quininer good point. I will create a follow-up pull request to https://github.com/libp2p/rust-libp2p/pull/1907.

**Review by romanb — APPROVED** [review]

**Comment by mxinden** [comment]
Looks like everything to be merged is merged. I will give folks a bit more time to comment. I plan to merge and cut the release later tonight in case nothing comes up. Thanks for the help @romanb and @quininer.

**Comment by mxinden** [comment]
For the record, the following crates have been tagged and published on crates.io:

- libp2p-core-0.27.0
- libp2p-deflate-0.27.0
- libp2p-dns-0.27.0
- libp2p-floodsub-0.27.0
- libp2p-gossipsub-0.27.0
- libp2p-identify-0.27.0
- libp2p-kad-0.28.0
- libp2p-mdns-0.28.0
- libp2p-mplex-0.27.0
- libp2p-noise-0.29.0
- libp2p-ping-0.27.0
- libp2p-plaintext-0.27.0
- libp2p-request-response-0.9.0
- libp2p-swarm-0.27.0
- libp2p-tcp-0.27.0
- libp2p-uds-0.27.0
- libp2p-wasm-ext-0.27.0
- libp2p-websocket-0.28.0
- libp2p-yamux-0.30.0
- multistream-select-0.10.0
- parity-multiaddr-0.11.0
- v0.34.0

**Pull request merged**
