### PR TITLE
Path 2: update rcgen to version 0.13.1

### PR DESCRIPTION
**Pull request by haurog**
As described in https://github.com/libp2p/rust-libp2p/issues/5590 this PR shows all the necessary changes for update path 2.
In this solution, rcgen and webrtc is updated to the newest version which makes substantial code changes necessary.

## Notes & open questions
I do not know the code base well enough to make sure I did not break anything here. All the tests (minus doc test) work and I also built lighthouse which depends on libp2p2-tls and it works flawlessly, so I do not think I broke anything obvious.

I did not change the documentation which is why doctest tests fail. 

## Change checklist

I did not do the changes described below. I can do this once it is decided which update Path is the one to go.

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — COMMENTED** [review]
Hi, and thanks for this! I definitely prefer this path over Path1 as I had started the same procedure on https://github.com/libp2p/rust-libp2p/pull/5448 but haven't yet had time to fix the tests, do you wanna take it over? that would be great!
Thanks!

**Comment by haurog** [comment]
That is awesome. I will definitely have a look at it and see if I can fix the test.

**Comment by jxs** [comment]
going to close this one then

**Comment by kayabaNerve** [comment]
Sorry for being out of the loop, yet why was this closed @jxs? rcgen wasn't updated from 0.11 so this remains a candidate. I'd guess the still open 0.12 PR is preferred yet I can't find any statement/documentation on that.

**Comment by dariusc93** [comment]
> Sorry for being out of the loop, yet why was this closed @jxs? rcgen wasn't updated from 0.11 so this remains a candidate. I'd guess the still open 0.12 PR is preferred yet I can't find any statement/documentation on that.

I believe this one was closed so it all can be done in https://github.com/libp2p/rust-libp2p/pull/5591.

**Comment by kayabaNerve** [comment]
That PR's last message was over a month ago, while this one was closed two weeks ago, hence my question _what caused an action two weeks ago_. If the answer is in fact that upgrading to 0.12 is preferred (my stated guess), I'd just appreciate confirmation and documented reasoning for it (as I'd assume upgrading to rcgen 0.13 would be generally preferred and jxs prior commented "I definitely prefer this path").

**Comment by jxs** [comment]
Hi @kayabaNerve, as referred above this was closed because #5591 was started first and @haurog stated that he was going to look into it as they mention on https://github.com/libp2p/rust-libp2p/pull/5592#issuecomment-2331939634.

Are you interested in  taking it over?

**Pull request closed without merging**
