### PR TITLE
fix(swarm): don't report `NewExternalAddrCandidate` if already confirmed

### PR DESCRIPTION
**Pull request by stormshield-frb**
## Description

Currently, `NewExternalAddrCandidate` events are emitted for every connections. However, we continue to get this event even when `autonat` has already confirmed that this address is external. So we should not continue to advertise the "candidate" event.

## Notes & open questions

We have made the changes in the `swarm` instead of `identify` because it does not make it necessary to duplicate the `ConfirmedExternalAddr` vector in the `identify` Behaviour. Moreover, if any future Behaviour emit `NewExternalAddrCandidate`, the same rule will also be applied. 

I had to edit the `autonat_v2` tests which were always expecting a `NewExternalAddrCandidate` but the address was already confirmed.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — APPROVED** [review]
Hi François, this LGTM! CC @umgefahren wdyt?

**Review by dariusc93 — APPROVED** [review]

**Comment by drHuangMHT** [comment]
This PR is not marked `send-it` but ready to merge(branch out-of-date aside), any problem here? @jxs

**Comment by drHuangMHT** [comment]
`cargo deny` failed due to #5596; `clippy(beta)` failed due to [`too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph) here:https://github.com/libp2p/rust-libp2p/blob/a2a281609a0a64b211f7917aa856924983b63200/misc/quick-protobuf-codec/src/lib.rs#L14-L16

**Comment by drHuangMHT** [comment]
@dariusc93 May you get the checks running again and merge this?

**Comment by drHuangMHT** [comment]
`send-it` lable must be applied in order to merge this automatically :pray:

**Pull request merged**
