### PR TITLE
Add support for twofish cipher

### PR DESCRIPTION
**Pull request by tomaka**
Adds support for the twofish cipher mode.

There are random data corruption in polkadot right now, and that might be a problem in the `aes` library.
Let's add support for twofish in secio, and later, once it's deployed, we can try using it in our local node to see if the data corruption goes away.

### CODE REVIEW

**Comment by tomaka** [comment]
This is an addition to the specifications of secio, as we add support for an algorithm that Go and JS don't support, with the name `TwofishCTR`.

I don't know if I should inform someone of that.
cc @mgoelzer 

The reason why I went for twofish and not blowfish (which Go and JS support) is because I couldn't find any CBC library in Rust.

**Comment by Stebalien** [comment]
This shouldn't *break* anything so I don't really have any objections. However, I don't think there are really any plans to add twofish support to the other implementations.

Are you just using this for testing?

**Comment by tomaka** [comment]
> This shouldn't break anything so I don't really have any objections.

Sure, but maybe we should document somewhere what the possible algorithms are, instead of having people figure out by reading the source code of the various implementations.

> Are you just using this for testing?

There's probably a bug in the AES crypto library we're using, and support for Blowfish would be too long to implement.

**Comment by burdges** [comment]
I suppose this does not matter given your reasons, but if it's only twofish in CTR mode being used then [that's just a stream cipher](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_(CTR)), so maybe ChaCha20 works too.

**Comment by tomaka** [comment]
Merging this because the Polkadot network is on fire, but we can keep discussing.

**Comment by Stebalien** [comment]
Yes, we should totally document this.

**Comment by mgoelzer** [comment]
> Yes, we should totally document this.

Unless we create an issue where docs people will see it, this will likely never be discovered by them.  I made one at https://github.com/libp2p/docs/issues/9.  AFAIK, libp2p currently has no docs repo or docs backlog (waffle or zen).  So we need to fix that.

**Pull request merged**
