### PR TITLE
Automatic fixes by cargo-fix

### PR DESCRIPTION
**Pull request by Demi-Marie**

### CODE REVIEW

**Comment by DemiMarie-parity** [comment]
Including `cargo fix` in CI would be great!

**Comment by twittner** [comment]
Does `&mut Context<'_>` convey useful information? I can see that returning a type that borrows data and writing `-> Foo<'_>` instead of `-> Foo` is a helpful signal but what does it add in argument position other than noise?

**Comment by DemiMarie-parity** [comment]
I have no idea, but I still don’t want to rely on deprecated features of rust.

**Comment by romanb** [comment]
@Demi-Marie If you could merge master, resolving the conflicts, I can go ahead and merge this,

**Comment by Demi-Marie** [comment]
@romanb I reset to master and reran `cargo fix --all --edition-idioms`.

**Pull request merged**
