### PR TITLE
feat: Backport interop test to rust-libp2p v048

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

Same as for the backport to `v.049.0`, we remove the QUIC, WebRTC and TLS capabilities from the JSON file which should give us a green interop test result.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — APPROVED** [review]
LGTM!

**Comment by MarcoPolo** [comment]
One downside is that this container will be an x86 image. Is it possible to publish both arm64 and x86 images?

**Comment by thomaseizinger** [comment]
> One downside is that this container will be an x86 image. Is it possible to publish both arm64 and x86 images?

Yes, we just need to cross-compile the binary.

**Comment by thomaseizinger** [comment]
> > One downside is that this container will be an x86 image. Is it possible to publish both arm64 and x86 images?
> 
> Yes, we just need to cross-compile the binary.

I've done this in the past. It is a bit involved so I'd like to defer it past the initial milestone of our interop tests.

Are you planning to run the tests on ARM as well? That is another variable in the matrix.

The way docker multi-arch images work is that the root image is just a manifest that points to one image per arch. Hence, you can `docker run` the same image on multiple arch's and it will always work.

Consequently, you need to publish 3[^1] images:

- one for x86
- one for arm64
- manifest image pointing to both

Doable, but a bit involved.

[^1]: `docker buildx` can help here but it is a convoluted setup so I wouldn't use it.

**Review by mxinden — APPROVED** [review]
I suggest targeting `v0.48` branch and not `release/v0.48.0`. `v0.48` branch does not yet exist, thus needs to be created off of the `v0.48.0` tag first.

Otherwise this looks good to me.

(I have not yet caught up on the discussion around checking in the `Cargo.lock` file, but that doesn't need to block this pull request.)

**Comment by thomaseizinger** [comment]
> I suggest targeting `v0.48` branch and not `release/v0.48.0`. `v0.48` branch does not yet exist, thus needs to be created off of the `v0.48.0` tag first.

Will do!

> I suggest targeting `v0.48` branch and not `release/v0.48.0`. `v0.48` branch does not yet exist, thus needs to be created off of the `v0.48.0` tag first.
> 
> Otherwise this looks good to me.
> 
> (I have not yet caught up on the discussion around checking in the `Cargo.lock` file, but that doesn't need to block this pull request.)

Without a lockfile, the builds aren't necessarily reproducible so I think we definitely need it for these tests. Overall, I came around to the view that we should have it for the library as well. It helps us manage potential semver breaks in our dependencies better. Otherwise those can block our CI pipeline which is annoying.

**Review by mxinden — APPROVED** [review]
Good to go from my end. Thanks for the work!

**Comment by thomaseizinger** [comment]
I ignored the clippy failures because it is too painful to backport them.

**Pull request merged**
