### PR TITLE
Add a network simulation test

### PR DESCRIPTION
**Pull request by tomaka**
Based on #487 

Adds a `net-test` crate in the workspace that simulates a network of 25 peers, each connected to each other. The peers each open 10 substreams, send "hello world" on it, then wait for the "hello world" back, then shutdown.

The network contains latency and random packet drops.

### CODE REVIEW

**Comment by dvdplm** [comment]
Do you know if there are any plans to make net-sim work on other platforms other than Linux?

**Comment by tomaka** [comment]
Probably not, but except for the emscripten code we don't have anything that cannot be simulated on a Linux host.

**Comment by tomaka** [comment]
I just realized that we can't really run the test in docker because the `netsim` crate needs access to the tunnel interface of the Linux kernel.

**Comment by tomaka** [comment]
Closing for inactivity.

**Pull request closed without merging**
