### PR TITLE
feat: introduce logging

### PR DESCRIPTION
**Pull request by drHuangMHT**
## Description

Introduce `logging` as dev depencency to add some abstraction over `tracing` and `tracing-subscriber` as discussed in #4992.

## Notes & open questions

Should this PR also include applying changes to other crates?

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by 0xJepsen** [comment]
Curious to see where this is at!

**Comment by jxs** [comment]
Hi @drHuangMHT sorry I missed this, can we do all in this PR and adapt all the other crates to the change?

**Comment by drHuangMHT** [comment]
Oh NO I forgot to tell git to always sign the commit, I'm on my new PC.

EDIT: I probably screwed something up here with all those changes coming out of nowhere.

**Comment by drHuangMHT** [comment]
Closing this in favor of #5725

**Pull request closed without merging**
