### PR TITLE
chore(ci): bump `cargo semver-checks` to `0.22.1`

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by b-zee** [comment]
Perhaps this is the issue?

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 89b756d1..8a876904 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,7 +60,7 @@ jobs:
       - uses: ./.github/actions/cargo-semver-checks
         if: steps.check-released.outputs.code == 200 # Workaround until https://github.com/obi1kenobi/cargo-semver-check/issues/146 is shipped.
         with:
-          crate: env.CRATE
+          crate: ${{ env.CRATE }}
 
       - name: Enforce no dependency on meta crate
         run: |
```

**Comment by thomaseizinger** [comment]
Did I mention that I absolutely hate untyped YAML programming? :angry: 

https://github.com/libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:5

**Comment by thomaseizinger** [comment]
> Did I mention that I absolutely hate untyped YAML programming? angry
> 
> [libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:5](https://github.com/libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:5)

Oh no, it does actually work, see: https://github.com/libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:8

**Comment by thomaseizinger** [comment]
> > Did I mention that I absolutely hate untyped YAML programming? angry
> > [libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:5](https://github.com/libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:5)
> 
> Oh no, it does actually work, see: [libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:8](https://github.com/libp2p/rust-libp2p/actions/runs/5610396967/jobs/10265498207?pr=4227#step:10:8)

NVM, it does not. This just shows that it would be in the env, but not that it is passed along.

**Comment by b-zee** [comment]
But if I literally run `cargo semver-checks check-release --package env.CRATE --verbose`, then I get the same `Error: no crates with library targets selected, nothing to semver-check`.

**Comment by b-zee** [comment]
> NVM, it does not. This just shows that it would be in the env, but not that it is passed along.

Then using `$CRATE` would also be a possibility. I saw this in some other actions as well. Might be neater anyway if that's consistent with other actions.

**Comment by b-zee** [comment]
Probably means the check actually never ran. `0.22.1` does exit with an error if no crate was selected:

> # What's Changed
> 
>  - Fix crash when checking crate without a lib target, or a workspace with such a crate.
>    - Such crates are now skipped by default. The tool exits with an error if there are no lib crates to check.

https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.22.1

**Comment by thomaseizinger** [comment]
Friendly ping @mxinden, this is awaiting review.

**Review by mxinden — APPROVED** [review]
Sorry for the delay. Thanks for the work @thomaseizinger and @b-zee.

**Pull request merged**
