### PR TITLE
Use pure-rust protoc

### LINKED ISSUE #183: Use the protobuf-codegen library to generate the protobuf at compile-time
This wasn't done before because this requires installing `protoc` on the machine that compiles `libp2p`.
However a new crate https://crates.io/crates/protobuf-codegen was released, and is pure Rust and can thus be used.

### PR DESCRIPTION
**Pull request by Vurich**
Closes #183 

This was basically a couple hours of `grep` + `sed` pipelines and running `cargo test` until it compiled

### CODE REVIEW

**Comment by tomaka** [comment]
Shouldn't we generate the Rust files in the directory pointed by the `OUT` env var (idiomatic cargo)?
https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-code-generation

**Comment by jamesray1** [comment]
Unfortunately (like #259), this is also failing on Windows for me.

I can confirm that [the diff locally between this PR and master is the same](https://gist.github.com/jamesray1/6bd12f74e047c73f04b986dd1f727efb). [Here is the cargo build output](https://gist.github.com/jamesray1/57b7f90f719d40611b43e41fb1ff954f).

**Comment by Vurich** [comment]
@jamesray1 

```
process didn't exit successfully: `C:\Users\James\jrl\target\debug\build\ring-4327ef7c900cd242\build-script-build` (exit code: 101)
```

This is ring failing and has nothing to do with `protoc`.

**Comment by tomaka** [comment]
I suggest to not close #183 (or reopen it after merging) so that we fix that correctly eventually.

**Pull request merged**
