### PR TITLE
chore: deprecate `void` crate

### PR DESCRIPTION
**Pull request by hanabi1224**
## Description

The `void` crate provides a `Void` type that is conceptually equivalent to the [`never` type(!)](https://doc.rust-lang.org/std/primitive.never.html). This PR tries to remove `void` crate from the dependency tree by replacing `void::Void` with [`std::convert::Infallible`](https://doc.rust-lang.org/std/convert/enum.Infallible.html) that will eventually become an alias of the `never` type(!) 

> This enum has the same role as [the ! “never” type](https://doc.rust-lang.org/std/primitive.never.html), which is unstable in this version of Rust. When ! is stabilized, we plan to make Infallible a type alias to it:

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by jxs — APPROVED** [review]
Hi, and thanks for this! :heart:

**Comment by dariusc93** [comment]
Might want to update the `Cargo.toml` to bump the versions on them :) 

EDIT: And changelogs

**Comment by dariusc93** [comment]
CC @hanabi1224 @jxs

**Comment by jxs** [comment]
Thanks for the reminding Darius, and I am sorry I didn't state explicitly why I moved ahead without asking for it.
I think in this case it's mostly redundant since it's only a dependency that we stop using, wdyt? 

Edit:
you are aright Darius, I missed that the `Cargo.toml` was not updated, and we probably should add entries on `CHANGELOG.md` for every PR that touches the code

**Pull request merged**
